// ============================================================
// BDD ACCENTS — verbes uniquement (é, è, ê, e sonnant [ɛ])
// inf = infinitif, temps = present/futur (affiche a l'ecran)
// niveau : facile (1 position testee) / difficile (2+ positions)
// ============================================================
const verbesAccents = [
  {"mot":"nous préférons","temps":"présent","inf":"préférer","cible":"é","niveau":"difficile"},
  {"mot":"nous préférons","temps":"présent","inf":"préférer","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"elle m'intéresse","temps":"présent","inf":"intéresser","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"elle m'intéresse","temps":"présent","inf":"intéresser","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elle m'étonne","temps":"présent","inf":"étonner","cible":"é","niveau":"facile"},
  {"mot":"je répare","temps":"présent","inf":"réparer","cible":"é","niveau":"facile"},
  {"mot":"elle présente","temps":"présent","inf":"présenter","cible":"é","niveau":"facile"},
  {"mot":"tu t'égares","temps":"présent","inf":"s'égarer","cible":"é","niveau":"facile"},
  {"mot":"il se décourage","temps":"présent","inf":"se décourager","cible":"é","niveau":"facile"},
  {"mot":"je stupéfie","temps":"présent","inf":"stupéfier","cible":"é","niveau":"facile"},
  {"mot":"j'appréhende","temps":"présent","inf":"appréhender","cible":"é","niveau":"facile"},
  {"mot":"je me réveille","temps":"présent","inf":"se réveiller","cible":"é","niveau":"facile"},
  {"mot":"je réfléchis","temps":"présent","inf":"réfléchir","cible":"é","niveau":"difficile"},
  {"mot":"je réfléchis","temps":"présent","inf":"réfléchir","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je réussis","temps":"présent","inf":"réussir","cible":"é","niveau":"facile"},
  {"mot":"elle représente","temps":"présent","inf":"représenter","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je vécus","temps":"présent","inf":"vivre","cible":"é","niveau":"facile"},
  {"mot":"tu régules","temps":"présent","inf":"réguler","cible":"é","niveau":"facile"},
  {"mot":"je préfère","temps":"présent","inf":"préférer","cible":"é","niveau":"difficile"},
  {"mot":"elle étincelle","temps":"présent","inf":"étinceler","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'apprécie","temps":"présent","inf":"apprécier","cible":"é","niveau":"facile"},
  {"mot":"j'atténue","temps":"présent","inf":"atténuer","cible":"é","niveau":"facile"},
  {"mot":"je bégaie","temps":"présent","inf":"bégayer","cible":"é","altRad":"bégaye","niveau":"facile"},
  {"mot":"je bénéficie","temps":"présent","inf":"bénéficier","cible":"é","niveau":"difficile"},
  {"mot":"je bénéficie","temps":"présent","inf":"bénéficier","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je différencie","temps":"présent","inf":"différencier","cible":"é","niveau":"facile"},
  {"mot":"je déblaie","temps":"présent","inf":"déblayer","cible":"é","altRad":"déblaye","niveau":"facile"},
  {"mot":"je défraie","temps":"présent","inf":"défrayer","cible":"é","altRad":"défraye","niveau":"facile"},
  {"mot":"je délaie","temps":"présent","inf":"délayer","cible":"é","altRad":"délaye","niveau":"facile"},
  {"mot":"j'égaie","temps":"présent","inf":"égayer","cible":"é","altRad":"égaye","niveau":"facile"},
  {"mot":"j'étaie","temps":"présent","inf":"étayer","cible":"é","altRad":"étaye","niveau":"facile"},
  {"mot":"je décrie","temps":"présent","inf":"décrier","cible":"é","niveau":"facile"},
  {"mot":"je défie","temps":"présent","inf":"défier","cible":"é","niveau":"facile"},
  {"mot":"je délie","temps":"présent","inf":"délier","cible":"é","niveau":"facile"},
  {"mot":"je dénie","temps":"présent","inf":"dénier","cible":"é","niveau":"facile"},
  {"mot":"je dénoue","temps":"présent","inf":"dénouer","cible":"é","niveau":"facile"},
  {"mot":"je déplie","temps":"présent","inf":"déplier","cible":"é","niveau":"facile"},
  {"mot":"je déploie","temps":"présent","inf":"déployer","cible":"é","niveau":"facile"},
  {"mot":"j'expédie","temps":"présent","inf":"expédier","cible":"é","niveau":"difficile"},
  {"mot":"j'expédie","temps":"présent","inf":"expédier","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'éberlue","temps":"présent","inf":"éberluer","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'épie","temps":"présent","inf":"épier","cible":"é","niveau":"facile"},
  {"mot":"j'éternue","temps":"présent","inf":"éternuer","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'étudie","temps":"présent","inf":"étudier","cible":"é","niveau":"facile"},
  {"mot":"j'évacue","temps":"présent","inf":"évacuer","cible":"é","niveau":"facile"},
  {"mot":"j'évalue","temps":"présent","inf":"évaluer","cible":"é","niveau":"facile"},
  {"mot":"j'évolue","temps":"présent","inf":"évoluer","cible":"é","niveau":"facile"},
  {"mot":"je maugrée","temps":"présent","inf":"maugréer","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je négocie","temps":"présent","inf":"négocier","cible":"é","niveau":"facile"},
  {"mot":"je privilégie","temps":"présent","inf":"privilégier","cible":"é","niveau":"facile"},
  {"mot":"je recrée","temps":"présent","inf":"recréer","pos":2,"cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je crée","temps":"présent","inf":"créer","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je remédie","temps":"présent","inf":"remédier","cible":"é","niveau":"facile"},
  {"mot":"je réconcilie","temps":"présent","inf":"réconcilier","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je répertorie","temps":"présent","inf":"répertorier","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je résilie","temps":"présent","inf":"résilier","cible":"é","niveau":"facile"},
  {"mot":"je spécifie","temps":"présent","inf":"spécifier","cible":"é","niveau":"facile"},
  {"mot":"je supplée","temps":"présent","inf":"suppléer","cible":"é","niveau":"facile"},
  {"mot":"je vérifie","temps":"présent","inf":"vérifier","cible":"é","niveau":"facile"},
  {"mot":"j'obéis","temps":"présent","inf":"obéir","cible":"é","niveau":"facile"},
  {"mot":"je guéris","temps":"présent","inf":"guérir","cible":"é","niveau":"facile"},
  {"mot":"j'établis","temps":"présent","inf":"établir","cible":"é","niveau":"facile"},
  {"mot":"je réagis","temps":"présent","inf":"réagir","cible":"é","niveau":"facile"},
  {"mot":"je réunis","temps":"présent","inf":"réunir","cible":"é","niveau":"facile"},
  {"mot":"j'élargis","temps":"présent","inf":"élargir","cible":"é","niveau":"facile"},
  {"mot":"je gémis","temps":"présent","inf":"gémir","cible":"é","niveau":"facile"},
  {"mot":"j'anéantis","temps":"présent","inf":"anéantir","cible":"é","niveau":"facile"},
  {"mot":"je définis","temps":"présent","inf":"définir","cible":"é","niveau":"facile"},
  {"mot":"je démolis","temps":"présent","inf":"démolir","cible":"é","niveau":"facile"},
  {"mot":"je désobéis","temps":"présent","inf":"désobéir","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"j'éblouis","temps":"présent","inf":"éblouir","cible":"é","niveau":"facile"},
  {"mot":"j'étourdis","temps":"présent","inf":"étourdir","cible":"é","niveau":"facile"},
  {"mot":"je frémis","temps":"présent","inf":"frémir","cible":"é","niveau":"facile"},
  {"mot":"je réjouis","temps":"présent","inf":"réjouir","cible":"é","niveau":"facile"},
  {"mot":"je rétablis","temps":"présent","inf":"rétablir","cible":"é","niveau":"facile"},
  {"mot":"je rétrécis","temps":"présent","inf":"rétrécir","cible":"é","niveau":"facile"},
  {"mot":"je dépéris","temps":"présent","inf":"dépérir","cible":"é","niveau":"difficile"},
  {"mot":"je dépéris","temps":"présent","inf":"dépérir","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"j'épaissis","temps":"présent","inf":"épaissir","cible":"é","niveau":"facile"},
  {"mot":"j'épanouis","temps":"présent","inf":"épanouir","cible":"é","niveau":"facile"},
  {"mot":"je flétris","temps":"présent","inf":"flétrir","cible":"é","niveau":"facile"},
  {"mot":"je découds","temps":"présent","inf":"découdre","cible":"é","niveau":"facile"},
  {"mot":"je défends","temps":"présent","inf":"défendre","cible":"é","niveau":"facile"},
  {"mot":"je démords","temps":"présent","inf":"démordre","cible":"é","niveau":"facile"},
  {"mot":"je désapprends","temps":"présent","inf":"désapprendre","cible":"é","niveau":"facile"},
  {"mot":"je détends","temps":"présent","inf":"détendre","cible":"é","niveau":"facile"},
  {"mot":"je détords","temps":"présent","inf":"détordre","cible":"é","niveau":"facile"},
  {"mot":"j'épands","temps":"présent","inf":"épandre","cible":"é","niveau":"facile"},
  {"mot":"j'étends","temps":"présent","inf":"étendre","cible":"é","niveau":"facile"},
  {"mot":"je prétends","temps":"présent","inf":"prétendre","cible":"é","niveau":"facile"},
  {"mot":"je réapprends","temps":"présent","inf":"réapprendre","cible":"é","niveau":"facile"},
  {"mot":"je réentends","temps":"présent","inf":"réentendre","cible":"é","niveau":"facile"},
  {"mot":"je répands","temps":"présent","inf":"répandre","cible":"é","niveau":"facile"},
  {"mot":"je réponds","temps":"présent","inf":"répondre","cible":"é","niveau":"facile"},
  {"mot":"je débats","temps":"présent","inf":"débattre","cible":"é","niveau":"facile"},
  {"mot":"je démets","temps":"présent","inf":"démettre","cible":"é","niveau":"facile"},
  {"mot":"j'émets","temps":"présent","inf":"émettre","cible":"é","niveau":"facile"},
  {"mot":"je télétransmets","temps":"présent","inf":"télétransmettre","cible":"é","niveau":"difficile"},
  {"mot":"je télétransmets","temps":"présent","inf":"télétransmettre","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je décris","temps":"présent","inf":"décrire","cible":"é","niveau":"facile"},
  {"mot":"je déduis","temps":"présent","inf":"déduire","cible":"é","niveau":"facile"},
  {"mot":"je défais","temps":"présent","inf":"défaire","cible":"é","niveau":"facile"},
  {"mot":"je démens","temps":"présent","inf":"démentir","cible":"é","niveau":"facile"},
  {"mot":"je dépeins","temps":"présent","inf":"dépeindre","cible":"é","niveau":"facile"},
  {"mot":"je déteins","temps":"présent","inf":"déteindre","cible":"é","niveau":"facile"},
  {"mot":"je détiens","temps":"présent","inf":"détenir","cible":"é","niveau":"facile"},
  {"mot":"je détruis","temps":"présent","inf":"détruire","cible":"é","niveau":"facile"},
  {"mot":"je méconnais","temps":"présent","inf":"méconnaître","cible":"é","niveau":"facile"},
  {"mot":"je déplais","temps":"présent","inf":"déplaire","cible":"é","niveau":"facile"},
  {"mot":"je préviens","temps":"présent","inf":"prévenir","cible":"é","niveau":"facile"},
  {"mot":"je prévois","temps":"présent","inf":"prévoir","cible":"é","niveau":"facile"},
  {"mot":"je réapparais","temps":"présent","inf":"réapparaître","cible":"é","niveau":"facile"},
  {"mot":"elle réapparaît","temps":"présent","inf":"réapparaître","altRad":"réapparait","cible":"é","niveau":"facile"},
  {"mot":"je récris","temps":"présent","inf":"récrire","cible":"é","niveau":"facile"},
  {"mot":"je réinscris","temps":"présent","inf":"réinscrire","cible":"é","niveau":"facile"},
  {"mot":"je réintroduis","temps":"présent","inf":"réintroduire","cible":"é","niveau":"facile"},
  {"mot":"je séduis","temps":"présent","inf":"séduire","cible":"é","niveau":"facile"},
  {"mot":"elle considère","temps":"présent","inf":"considérer","cible":"è","niveau":"facile"},
  {"mot":"elle digère","temps":"présent","inf":"digérer","cible":"è","niveau":"facile"},
  {"mot":"je modèle","temps":"présent","inf":"modeler","cible":"è","niveau":"facile"},
  {"mot":"j'achète","temps":"présent","inf":"acheter","cible":"è","niveau":"facile"},
  {"mot":"je gèle","temps":"présent","inf":"geler","cible":"è","niveau":"facile"},
  {"mot":"je lève","temps":"présent","inf":"lever","cible":"è","niveau":"facile"},
  {"mot":"je pèse","temps":"présent","inf":"peser","cible":"è","niveau":"facile"},
  {"mot":"je libère","temps":"présent","inf":"libérer","cible":"è","niveau":"facile"},
  {"mot":"je tolère","temps":"présent","inf":"tolérer","cible":"è","niveau":"facile"},
  {"mot":"je modère","temps":"présent","inf":"modérer","cible":"è","niveau":"facile"},
  {"mot":"je coopère","temps":"présent","inf":"coopérer","cible":"è","niveau":"facile"},
  {"mot":"j'adhère","temps":"présent","inf":"adhérer","cible":"è","niveau":"facile"},
  {"mot":"je transfère","temps":"présent","inf":"transférer","cible":"è","niveau":"facile"},
  {"mot":"je prolifère","temps":"présent","inf":"proliférer","cible":"è","niveau":"facile"},
  {"mot":"je diffère","temps":"présent","inf":"différer","cible":"è","niveau":"facile"},
  {"mot":"j'opère","temps":"présent","inf":"opérer","cible":"è","niveau":"facile"},
  {"mot":"j'altère","temps":"présent","inf":"altérer","cible":"è","niveau":"facile"},
  {"mot":"je cède","temps":"présent","inf":"céder","cible":"è","niveau":"facile"},
  {"mot":"je possède","temps":"présent","inf":"posséder","cible":"è","niveau":"facile"},
  {"mot":"je succède","temps":"présent","inf":"succéder","cible":"è","niveau":"facile"},
  {"mot":"je procède","temps":"présent","inf":"procéder","cible":"è","niveau":"facile"},
  {"mot":"je concède","temps":"présent","inf":"concéder","cible":"è","niveau":"facile"},
  {"mot":"je complète","temps":"présent","inf":"compléter","cible":"è","niveau":"facile"},
  {"mot":"j'interprète","temps":"présent","inf":"interpréter","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je protège","temps":"présent","inf":"protéger","cible":"è","niveau":"facile"},
  {"mot":"j'abrège","temps":"présent","inf":"abréger","cible":"è","niveau":"facile"},
  {"mot":"j'assiège","temps":"présent","inf":"assiéger","cible":"è","niveau":"facile"},
  {"mot":"tu craquelles","temps":"présent","inf":"craqueler","cible":"e","altRad":"craquèles","niveau":"difficile"},
  {"mot":"je ficelle","temps":"présent","inf":"ficeler","cible":"e","altRad":"ficèle","niveau":"difficile"},
  {"mot":"il ficelle","temps":"présent","inf":"ficeler","cible":"e","altRad":"ficèle","niveau":"difficile"},
  {"mot":"tu harcèles","temps":"présent","inf":"harceler","cible":"è","niveau":"facile"},
  {"mot":"on jumelle","temps":"présent","inf":"jumeler","cible":"e","altRad":"jumèle","niveau":"difficile"},
  {"mot":"tu craquelleras","temps":"futur","inf":"craqueler","cible":"e","altRad":"craquèleras","niveau":"difficile"},
  {"mot":"il débossellera","temps":"futur","inf":"débosseler","cible":"e","altRad":"débossèlera","niveau":"difficile"},
  {"mot":"ils épelleront","temps":"futur","inf":"épeler","cible":"e","altRad":"épèleront","niveau":"difficile"},
  {"mot":"nous ficellerons","temps":"futur","inf":"ficeler","cible":"e","altRad":"ficèlerons","niveau":"difficile"},
  {"mot":"vous harcèlerez","temps":"futur","inf":"harceler","cible":"è","niveau":"facile"},
  {"mot":"nous jumellerons","temps":"futur","inf":"jumeler","cible":"e","altRad":"jumèlerons","niveau":"difficile"},
  {"mot":"je protègerai","temps":"futur","inf":"protéger","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je tolèrerai","temps":"futur","inf":"tolérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je coopèrerai","temps":"futur","inf":"coopérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'exagèrerai","temps":"futur","inf":"exagérer","pos":2,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'opèrerai","temps":"futur","inf":"opérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je cèderai","temps":"futur","inf":"céder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je possèderai","temps":"futur","inf":"posséder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je procèderai","temps":"futur","inf":"procéder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je succèderai","temps":"futur","inf":"succéder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je complèterai","temps":"futur","inf":"compléter","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'espère","temps":"présent","inf":"espérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'interfère","temps":"présent","inf":"interférer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je chancelle","temps":"présent","inf":"chanceler","cible":"e","altRad":"chancèle","niveau":"difficile"},
  {"mot":"je chancellerai","temps":"futur","inf":"chanceler","cible":"e","altRad":"chancèlerai","niveau":"difficile"},
  {"mot":"j'arrête","temps":"présent","inf":"arrêter","cible":"ê","info":"de la famille d'arrestation","niveau":"facile"},
  {"mot":"je m'entête","temps":"présent","inf":"s'entêter","pos":2,"cible":"ê","info":"vient du latin testa","niveau":"facile"},
  {"mot":"elle fête","temps":"présent","inf":"fêter","cible":"ê","info":"de la famille de festif","niveau":"facile"},
  {"mot":"être","temps":"infinitif","inf":"être","cible":"ê","info":"de la famille de je suis, nous sommes, elles sont","niveau":"facile"},
  {"mot":"tu rêves","temps":"présent","inf":"rêver","cible":"ê","niveau":"facile"},
  {"mot":"tu m'embêtes","temps":"présent","inf":"embêter","pos":2,"cible":"ê","info":"de la famille de bestial, bestiaux","niveau":"facile"},
  {"mot":"il se défenêtre","temps":"présent","inf":"se défenêtrer","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"il se défenêtre","temps":"présent","inf":"se défenêtrer","pos":3,"cible":"ê","info":"de la famille de défenestrer","niveau":"difficile"},
  {"mot":"elle tempête","temps":"présent","inf":"tempêter","pos":2,"cible":"ê","info":"de la famille de tempest en anglais","niveau":"facile"},
  {"mot":"il crêpe","temps":"présent","inf":"crêper","cible":"ê","info":"vient du latin crispus","niveau":"facile"},
  {"mot":"elles viennent","temps":"présent","inf":"venir","cible":"e","niveau":"difficile"},
  {"mot":"elles parviennent","temps":"présent","inf":"parvenir","cible":"e","niveau":"difficile"},
  {"mot":"elles reviennent","temps":"présent","inf":"revenir","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles tiennent","temps":"présent","inf":"tenir","cible":"e","niveau":"difficile"},
  {"mot":"elles retiennent","temps":"présent","inf":"retenir","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles détiennent","temps":"présent","inf":"détenir","cible":"e","niveau":"difficile"},
  {"mot":"elles comprennent","temps":"présent","inf":"comprendre","cible":"e","niveau":"difficile"},
  {"mot":"elles reprennent","temps":"présent","inf":"reprendre","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles apprennent","temps":"présent","inf":"apprendre","cible":"e","niveau":"difficile"},
  {"mot":"j'interprète","temps":"présent","inf":"interpréter","cible":"e","niveau":"difficile"},
      {"mot":"j'interpelle","temps":"présent","inf":"interpeller","cible":"e","niveau":"difficile"},
  {"mot":"j'interpelle","temps":"présent","inf":"interpeller","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je rejette","temps":"présent","inf":"rejeter","pos":2,"cible":"e","niveau":"difficile"},
    {"mot":"je jette","temps":"présent","inf":"jeter","cible":"e","niveau":"difficile"},
  {"mot":"je projette","temps":"présent","inf":"projeter","cible":"e","niveau":"difficile"},
  {"mot":"j'espère","temps":"présent","inf":"espérer","cible":"e","niveau":"difficile"},
  {"mot":"j'interfère","temps":"présent","inf":"interférer","cible":"e","niveau":"difficile"},
  {"mot":"j'exagèrerai","temps":"futur","inf":"exagérer","cible":"e","altRad":"exagérerai","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'appelle","temps":"présent","inf":"appeler","cible":"e","niveau":"difficile"},
  {"mot":"je rappelle","temps":"présent","inf":"rappeler","cible":"e","niveau":"difficile"},
  {"mot":"je persévèrerai","temps":"futur","inf":"persévérer","cible":"e","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","temps":"futur","inf":"persévérer","pos":2,"cible":"é","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","temps":"futur","inf":"persévérer","pos":3,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je préférerai","temps":"futur","inf":"préférer","cible":"é","altRad":"préfèrerai","niveau":"difficile"},
  {"mot":"je préférerai","temps":"futur","inf":"préférer","pos":2,"cible":"é","altRad":"préfèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'accélèrerai","temps":"futur","inf":"accélérer","cible":"é","altRad":"accélérerai","niveau":"difficile"},
  {"mot":"j'accélèrerai","temps":"futur","inf":"accélérer","pos":2,"cible":"è","altRad":"accélérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je récupèrerai","temps":"futur","inf":"récupérer","cible":"é","altRad":"récupérerai","niveau":"difficile"},
  {"mot":"je récupèrerai","temps":"futur","inf":"récupérer","pos":2,"cible":"è","altRad":"récupérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je génèrerai","temps":"futur","inf":"générer","cible":"é","altRad":"générerai","niveau":"difficile"},
  {"mot":"je génèrerai","temps":"futur","inf":"générer","pos":2,"cible":"è","altRad":"générerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je répèterai","temps":"futur","inf":"répéter","cible":"é","altRad":"répéterai","niveau":"difficile"},
  {"mot":"je répèterai","temps":"futur","inf":"répéter","pos":2,"cible":"è","altRad":"répéterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je réfèrerai","temps":"futur","inf":"référer","cible":"é","altRad":"référerai","niveau":"difficile"},
  {"mot":"je réfèrerai","temps":"futur","inf":"référer","pos":2,"cible":"è","altRad":"référerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je pénétrerai","temps":"futur","inf":"pénétrer","cible":"é","altRad":"pénètrerai","niveau":"difficile"},
  {"mot":"je pénétrerai","temps":"futur","inf":"pénétrer","pos":2,"cible":"é","altRad":"pénètrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"je déléguerai","temps":"futur","inf":"déléguer","cible":"é","altRad":"délèguerai","niveau":"difficile"},
  {"mot":"je déléguerai","temps":"futur","inf":"déléguer","pos":2,"cible":"é","altRad":"délèguerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'interprèterai","temps":"futur","inf":"interpréter","cible":"e","altRad":"interpréterai","niveau":"difficile"},
  {"mot":"j'interprèterai","temps":"futur","inf":"interpréter","pos":2,"cible":"è","altRad":"interpréterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'espèrerai","temps":"futur","inf":"espérer","cible":"e","altRad":"espérerai","niveau":"difficile"},
  {"mot":"j'espèrerai","temps":"futur","inf":"espérer","pos":2,"cible":"è","altRad":"espérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je libèrerai","temps":"futur","inf":"libérer","cible":"è","altRad":"libérerai","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"il débossellera","temps":"futur","inf":"débosseler","cible":"é","niveau":"difficile"},
  {"mot":"j'accélérerai","temps":"futur","inf":"accélérer","cible":"é","altRad":"accélèrerai","niveau":"difficile"},
  {"mot":"j'accélérerai","temps":"futur","inf":"accélérer","pos":2,"cible":"é","altRad":"accélèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"elle répète","temps":"présent","inf":"répéter","cible":"é","niveau":"difficile"},
  {"mot":"elle répète","temps":"présent","inf":"répéter","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je délègue","temps":"présent","inf":"déléguer","cible":"é","niveau":"difficile"},
  {"mot":"je délègue","temps":"présent","inf":"déléguer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je génère","temps":"présent","inf":"générer","cible":"é","niveau":"difficile"},
  {"mot":"je génère","temps":"présent","inf":"générer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je récupère","temps":"présent","inf":"récupérer","cible":"é","niveau":"difficile"},
  {"mot":"je récupère","temps":"présent","inf":"récupérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je réfère","temps":"présent","inf":"référer","cible":"é","niveau":"difficile"},
  {"mot":"je réfère","temps":"présent","inf":"référer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je persévère","temps":"présent","inf":"persévérer","cible":"e","niveau":"difficile"},
  {"mot":"je persévère","temps":"présent","inf":"persévérer","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je persévère","temps":"présent","inf":"persévérer","pos":3,"cible":"è","niveau":"difficile"},
  {"mot":"j'accélère","temps":"présent","inf":"accélérer","cible":"é","niveau":"difficile"},
  {"mot":"j'accélère","temps":"présent","inf":"accélérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je préfère","temps":"présent","inf":"préférer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'élève","temps":"présent","inf":"élever","cible":"é","niveau":"difficile"},
  {"mot":"j'élève","temps":"présent","inf":"élever","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"ils épellent","temps":"présent","inf":"épeler","cible":"é","niveau":"difficile"},
  {"mot":"ils épellent","temps":"présent","inf":"épeler","pos":2,"cible":"e","altRad":"épèlent","niveau":"difficile"},
  {"mot":"nous acquérons","temps":"présent","inf":"acquérir","cible":"é","niveau":"facile"},
  {"mot":"nous conquérons","temps":"présent","inf":"conquérir","cible":"é","niveau":"facile"},
  {"mot":"nous requérons","temps":"présent","inf":"requérir","cible":"é","niveau":"facile"},
  {"mot":"je réadmets","temps":"présent","inf":"réadmettre","cible":"é","niveau":"facile"},
  {"mot":"je réduis","temps":"présent","inf":"réduire","cible":"é","niveau":"facile"},
  {"mot":"je résous","temps":"présent","inf":"résoudre","cible":"é","niveau":"facile"},
  {"mot":"nous nous enquérons","temps":"présent","inf":"s'enquérir","cible":"é","niveau":"facile"},
  {"mot":"je m'écrie","temps":"présent","inf":"s'écrier","cible":"é","niveau":"facile"},
  {"mot":"je m'éprends","temps":"présent","inf":"s'éprendre","cible":"é","niveau":"facile"},
  {"mot":"je m'étends","temps":"présent","inf":"s'étendre","cible":"é","niveau":"facile"},
  {"mot":"je me débats","temps":"présent","inf":"se débattre","cible":"é","niveau":"facile"},
  {"mot":"je me découds","temps":"présent","inf":"se découdre","cible":"é","niveau":"facile"},
  {"mot":"je me défends","temps":"présent","inf":"se défendre","cible":"é","niveau":"facile"},
  {"mot":"je me démets","temps":"présent","inf":"se démettre","cible":"é","niveau":"facile"},
  {"mot":"je me détends","temps":"présent","inf":"se détendre","cible":"é","niveau":"facile"},
  {"mot":"je me dévoue","temps":"présent","inf":"se dévouer","cible":"é","niveau":"facile"},
  {"mot":"je me méfie","temps":"présent","inf":"se méfier","cible":"é","niveau":"facile"},
  {"mot":"je me méprends","temps":"présent","inf":"se méprendre","cible":"é","niveau":"facile"},
  {"mot":"je me réfugie","temps":"présent","inf":"se réfugier","cible":"é","niveau":"facile"},
  {"mot":"je me réjouis","temps":"présent","inf":"se réjouir","cible":"é","niveau":"facile"},
  {"mot":"je me réponds","temps":"présent","inf":"se répondre","cible":"é","niveau":"facile"},
  {"mot":"j'écris","temps":"présent","inf":"écrire","cible":"é","niveau":"facile"},
  {"mot":"j'émeus","temps":"présent","inf":"émouvoir","cible":"é","niveau":"facile"},
  {"mot":"je réécris","temps":"présent","inf":"réécrire","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"je réécris","temps":"présent","inf":"réécrire","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je réélis","temps":"présent","inf":"réélire","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"je réélis","temps":"présent","inf":"réélire","pos":2,"cible":"é","niveau":"difficile"},

  {"mot":"j'examine","temps":"présent","inf":"examiner","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'excite","temps":"présent","inf":"exciter","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'existe","temps":"présent","inf":"exister","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'exige","temps":"présent","inf":"exiger","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'explique","temps":"présent","inf":"expliquer","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'exploite","temps":"présent","inf":"exploiter","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'explore","temps":"présent","inf":"explorer","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'expose","temps":"présent","inf":"exposer","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'exprime","temps":"présent","inf":"exprimer","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},
  {"mot":"j'expulse","temps":"présent","inf":"expulser","cible":"e","info":"Devant un x, le e s'ouvre en [ɛ] sans accent.","niveau":"difficile"},

  {"mot":"je perds","temps":"présent","inf":"perdre","cible":"e","niveau":"facile"},
  {"mot":"elle descend","temps":"présent","inf":"descendre","cible":"e","niveau":"facile"},
  {"mot":"je prêche","temps":"présent","inf":"prêcher","cible":"ê","niveau":"facile"},
  {"mot":"j'apprête","temps":"présent","inf":"apprêter","cible":"ê","niveau":"facile"},
  {"mot":"je vêts","temps":"présent","inf":"vêtir","cible":"ê","info":"de la famille de vestimentaire","niveau":"facile"},
  {"mot":"je quête","temps":"présent","inf":"quêter","cible":"ê","niveau":"facile"},
  {"mot":"j'empêche","temps":"présent","inf":"empêcher","cible":"e","info":"E initial fermé par une consonne, comme dans persévérer.","niveau":"difficile"},
  {"mot":"j'empêche","temps":"présent","inf":"empêcher","cible":"ê","niveau":"difficile"},
  {"mot":"j'enquête","temps":"présent","inf":"enquêter","cible":"e","info":"E initial fermé par une consonne, comme dans persévérer.","niveau":"difficile"},
  {"mot":"j'enquête","temps":"présent","inf":"enquêter","cible":"ê","niveau":"difficile"},
];