// ============================================================
// dataFuturCondiPron.js — Verbes pronominaux futur/conditionnel
// ============================================================

const verbesFuturPron1 = [
{
  infinitif: "s'approprier",
  groupe: 1,
  pronominal: true,
  radicalJe: "m'approprier",
  radicalTu: "t'approprier",
  radicalIl: "s'approprier",
  radicalNous: "nous approprier",
  radicalVous: "vous approprier",
  radicalPluriel: "s'approprier",
},
{
  infinitif: "s'endormir",
  groupe: 3,
  pronominal: true,
  radicalJe: "m'endormir",
  radicalTu: "t'endormir",
  radicalIl: "s'endormir",
  radicalNous: "nous endormir",
  radicalVous: "vous endormir",
  radicalPluriel: "s'endormir",
},
{
  infinitif: "s'enhardir",
  groupe: 2,
  pronominal: true,
  radicalJe: "m'enhardir",
  radicalTu: "t'enhardir",
  radicalIl: "s'enhardir",
  radicalNous: "nous enhardir",
  radicalVous: "vous enhardir",
  radicalPluriel: "s'enhardir",
},
{
  infinitif: "s'extasier",
  groupe: 1,
  pronominal: true,
  radicalJe: "m'extasier",
  radicalTu: "t'extasier",
  radicalIl: "s'extasier",
  radicalNous: "nous extasier",
  radicalVous: "vous extasier",
  radicalPluriel: "s'extasier",
},
{
  infinitif: "s'écrier",
  groupe: 1,
  pronominal: true,
  radicalJe: "m'écrier",
  radicalTu: "t'écrier",
  radicalIl: "s'écrier",
  radicalNous: "nous écrier",
  radicalVous: "vous écrier",
  radicalPluriel: "s'écrier",
},
{
  infinitif: "s'éprendre",
  groupe: 3,
  pronominal: true,
  radicalJe: "m'éprendr",
  radicalTu: "t'éprendr",
  radicalIl: "s'éprendr",
  radicalNous: "nous éprendr",
  radicalVous: "vous éprendr",
  radicalPluriel: "s'éprendr",
},
{
  infinitif: "se blottir",
  groupe: 2,
  pronominal: true,
  radicalJe: "me blottir",
  radicalTu: "te blottir",
  radicalIl: "se blottir",
  radicalNous: "nous blottir",
  radicalVous: "vous blottir",
  radicalPluriel: "se blottir",
},
{
  infinitif: "se bonifier",
  groupe: 1,
  pronominal: true,
  radicalJe: "me bonifier",
  radicalTu: "te bonifier",
  radicalIl: "se bonifier",
  radicalNous: "nous bonifier",
  radicalVous: "vous bonifier",
  radicalPluriel: "se bonifier",
},
{
  infinitif: "se dédire",
  groupe: 3,
  pronominal: true,
  radicalJe: "me dédir",
  radicalTu: "te dédir",
  radicalIl: "se dédir",
  radicalNous: "nous dédir",
  radicalVous: "vous dédir",
  radicalPluriel: "se dédir",
},
{
  infinitif: "se départir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me départir",
  radicalTu: "te départir",
  radicalIl: "se départir",
  radicalNous: "nous départir",
  radicalVous: "vous départir",
  radicalPluriel: "se départir",
},
{
  infinitif: "se dévouer",
  groupe: 1,
  pronominal: true,
  radicalJe: "me dévouer",
  radicalTu: "te dévouer",
  radicalIl: "se dévouer",
  radicalNous: "nous dévouer",
  radicalVous: "vous dévouer",
  radicalPluriel: "se dévouer",
},
{
  infinitif: "se marier",
  groupe: 1,
  pronominal: true,
  radicalJe: "me marier",
  radicalTu: "te marier",
  radicalIl: "se marier",
  radicalNous: "nous marier",
  radicalVous: "vous marier",
  radicalPluriel: "se marier",
},
{
  infinitif: "se morfondre",
  groupe: 3,
  pronominal: true,
  radicalJe: "me morfondr",
  radicalTu: "te morfondr",
  radicalIl: "se morfondr",
  radicalNous: "nous morfondr",
  radicalVous: "vous morfondr",
  radicalPluriel: "se morfondr",
},
{
  infinitif: "se méfier",
  groupe: 1,
  pronominal: true,
  radicalJe: "me méfier",
  radicalTu: "te méfier",
  radicalIl: "se méfier",
  radicalNous: "nous méfier",
  radicalVous: "vous méfier",
  radicalPluriel: "se méfier",
},
{
  infinitif: "se méprendre",
  groupe: 3,
  pronominal: true,
  radicalJe: "me méprendr",
  radicalTu: "te méprendr",
  radicalIl: "se méprendr",
  radicalNous: "nous méprendr",
  radicalVous: "vous méprendr",
  radicalPluriel: "se méprendr",
},
{
  infinitif: "se rendre",
  groupe: 3,
  pronominal: true,
  radicalJe: "me rendr",
  radicalTu: "te rendr",
  radicalIl: "se rendr",
  radicalNous: "nous rendr",
  radicalVous: "vous rendr",
  radicalPluriel: "se rendr",
},
{
  infinitif: "se repentir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me repentir",
  radicalTu: "te repentir",
  radicalIl: "se repentir",
  radicalNous: "nous repentir",
  radicalVous: "vous repentir",
  radicalPluriel: "se repentir",
},
{
  infinitif: "se réfugier",
  groupe: 1,
  pronominal: true,
  radicalJe: "me réfugier",
  radicalTu: "te réfugier",
  radicalIl: "se réfugier",
  radicalNous: "nous réfugier",
  radicalVous: "vous réfugier",
  radicalPluriel: "se réfugier",
},
{
  infinitif: "se soucier",
  groupe: 1,
  pronominal: true,
  radicalJe: "me soucier",
  radicalTu: "te soucier",
  radicalIl: "se soucier",
  radicalNous: "nous soucier",
  radicalVous: "vous soucier",
  radicalPluriel: "se soucier",
},
{
  infinitif: "se taire",
  groupe: 3,
  pronominal: true,
  radicalJe: "me tair",
  radicalTu: "te tair",
  radicalIl: "se tair",
  radicalNous: "nous tair",
  radicalVous: "vous tair",
  radicalPluriel: "se tair",
},
{
  infinitif: "se vêtir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me vêtir",
  radicalTu: "te vêtir",
  radicalIl: "se vêtir",
  radicalNous: "nous vêtir",
  radicalVous: "vous vêtir",
  radicalPluriel: "se vêtir",
},
{
  infinitif: "s'ensuivre",
  groupe: 3,
  pronominal: true,
  sujetsPossibles: ["il"],
  radicalFut: "s'ensuivr",
},
];

const verbesFuturPron2 = [
{
  infinitif: "se recueillir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me recueiller",
  radicalTu: "te recueiller",
  radicalIl: "se recueiller",
  radicalNous: "nous recueiller",
  radicalVous: "vous recueiller",
  radicalPluriel: "se recueiller",
},
{
  infinitif: "s'abstenir",
  groupe: 3,
  pronominal: true,
  radicalJe: "m'abstiendr",
  radicalTu: "t'abstiendr",
  radicalIl: "s'abstiendr",
  radicalNous: "nous abstiendr",
  radicalVous: "vous abstiendr",
  radicalPluriel: "s'abstiendr",
},
{
  infinitif: "s'apitoyer",
  groupe: 1,
  pronominal: true,
  radicalJe: "m'apitoier",
  radicalTu: "t'apitoier",
  radicalIl: "s'apitoier",
  radicalNous: "nous apitoier",
  radicalVous: "vous apitoier",
  radicalPluriel: "s'apitoier",
},
{
  infinitif: "s'enfuir",
  groupe: 3,
  pronominal: true,
  radicalJe: "m'enfuir",
  radicalTu: "t'enfuir",
  radicalIl: "s'enfuir",
  radicalNous: "nous enfuir",
  radicalVous: "vous enfuir",
  radicalPluriel: "s'enfuir",
},
{
  infinitif: "s'enquérir",
  groupe: 3,
  pronominal: true,
  radicalJe: "m'enquerr",
  radicalTu: "t'enquerr",
  radicalIl: "s'enquerr",
  radicalNous: "nous enquerr",
  radicalVous: "vous enquerr",
  radicalPluriel: "s'enquerr",
},
{
  infinitif: "se frayer",
  groupe: 1,
  pronominal: true,
  radicalJe: "me fraier",
  radicalTu: "te fraier",
  radicalIl: "se fraier",
  radicalNous: "nous fraier",
  radicalVous: "vous fraier",
  radicalPluriel: "se fraier",
},
{
  infinitif: "se recueiller",
  groupe: 3,
  pronominal: true,
  radicalJe: "me recueiller",
  radicalTu: "te recueiller",
  radicalIl: "se recueiller",
  radicalNous: "nous recueiller",
  radicalVous: "vous recueiller",
  radicalPluriel: "se recueiller",
},
{
  infinitif: "se rendormir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me rendormir",
  radicalTu: "te rendormir",
  radicalIl: "se rendormir",
  radicalNous: "nous rendormir",
  radicalVous: "vous rendormir",
  radicalPluriel: "se rendormir",
},
{
  infinitif: "se souvenir",
  groupe: 3,
  pronominal: true,
  radicalJe: "me souviendr",
  radicalTu: "te souviendr",
  radicalIl: "se souviendr",
  radicalNous: "nous souviendr",
  radicalVous: "vous souviendr",
  radicalPluriel: "se souviendr",
},
];
