// ================================================================
// BDD PARTICIPE PASSE - JEU 2 : accord du feminin
// rad + cible reconstituent le participe passe masculin (rad+cible)
// cible : is / it / us / ait (famille faire) / int (nasale eint-aint-oint)
// ex = phrase porteuse (nom + accord feminin)
// niveau : facile / difficile
// ================================================================
const verbesPP_jeu2 = [
  {"inf":"acquérir","rad":"acqu","ppFem":"acquise","cible":"is","ex":"une décision acquise","niveau":"facile"},
  {"inf":"apprendre","rad":"appr","ppFem":"apprise","cible":"is","ex":"une décision apprise","niveau":"facile"},
  {"inf":"s'asseoir","rad":"ass","ppFem":"assise","cible":"is","ex":"une personne assise","niveau":"facile","pronominal":true},
  {"inf":"astreindre","rad":"astre","ppFem":"astreinte","cible":"int","ex":"une décision astreinte","niveau":"difficile"},
  {"inf":"atteindre","rad":"atte","ppFem":"atteinte","cible":"int","ex":"une décision atteinte","niveau":"facile"},
  {"inf":"ceindre","rad":"ce","ppFem":"ceinte","cible":"int","ex":"la maison ceinte","niveau":"difficile"},
  {"inf":"circonscrire","rad":"circonscr","ppFem":"circonscrite","cible":"it","ex":"une décision circonscrite","niveau":"difficile"},
  {"inf":"comprendre","rad":"compr","ppFem":"comprise","cible":"is","ex":"une décision comprise","niveau":"facile"},
  {"inf":"conduire","rad":"condu","ppFem":"conduite","cible":"it","ex":"une décision conduite","niveau":"facile"},
  {"inf":"confire","rad":"conf","ppFem":"confite","cible":"it","ex":"la carotte confite","niveau":"difficile"},
  {"inf":"conquérir","rad":"conqu","ppFem":"conquise","cible":"is","ex":"une décision conquise","niveau":"facile"},
  {"inf":"construire","rad":"constru","ppFem":"construite","cible":"it","ex":"la maison construite","niveau":"facile"},
  {"inf":"contraindre","rad":"contra","ppFem":"contrainte","cible":"int","ex":"une décision contrainte","niveau":"difficile"},
  {"inf":"contredire","rad":"contred","ppFem":"contredite","cible":"it","ex":"une parole contredite","niveau":"facile"},
  {"inf":"contrefaire","rad":"contref","ppFem":"contrefaite","cible":"ait","ex":"une décision contrefaite","niveau":"difficile"},
  {"inf":"craindre","rad":"cra","ppFem":"crainte","cible":"int","ex":"une décision crainte","niveau":"facile"},
  {"inf":"cuire","rad":"cu","ppFem":"cuite","cible":"it","ex":"la carotte cuite","niveau":"facile"},
  {"inf":"dire","rad":"d","ppFem":"dite","cible":"it","ex":"une parole dite","niveau":"facile"},
  {"inf":"décrire","rad":"décr","ppFem":"décrite","cible":"it","ex":"la lettre décrite","niveau":"facile"},
  {"inf":"déduire","rad":"dédu","ppFem":"déduite","cible":"it","ex":"une décision déduite","niveau":"facile"},
  {"inf":"défaire","rad":"déf","ppFem":"défaite","cible":"ait","ex":"une décision défaite","niveau":"facile"},
  {"inf":"dépeindre","rad":"dépe","ppFem":"dépeinte","cible":"int","ex":"la maison dépeinte","niveau":"difficile"},
  {"inf":"déteindre","rad":"déte","ppFem":"déteinte","cible":"int","ex":"la maison déteinte","niveau":"facile"},
  {"inf":"détruire","rad":"détru","ppFem":"détruite","cible":"it","ex":"la maison détruite","niveau":"facile"},
  {"inf":"enduire","rad":"endu","ppFem":"enduite","cible":"it","ex":"la maison enduite","niveau":"difficile"},
  {"inf":"enfreindre","rad":"enfre","ppFem":"enfreinte","cible":"int","ex":"une décision enfreinte","niveau":"difficile"},
  {"inf":"enjoindre","rad":"enjo","ppFem":"enjointe","cible":"int","ex":"une décision enjointe","niveau":"difficile"},
  {"inf":"entreprendre","rad":"entrepr","ppFem":"entreprise","cible":"is","ex":"une décision entreprise","niveau":"facile"},
  {"inf":"faire","rad":"f","ppFem":"faite","cible":"ait","ex":"une décision faite","niveau":"facile"},
  {"inf":"feindre","rad":"fe","ppFem":"feinte","cible":"int","ex":"une parole feinte","niveau":"difficile"},
  {"inf":"geindre","rad":"ge","ppFem":"geinte","cible":"int","ex":"une parole geinte","niveau":"difficile"},
  {"inf":"induire","rad":"indu","ppFem":"induite","cible":"it","ex":"une décision induite","niveau":"difficile"},
  {"inf":"inscrire","rad":"inscr","ppFem":"inscrite","cible":"it","ex":"la lettre inscrite","niveau":"facile"},
  {"inf":"instruire","rad":"instru","ppFem":"instruite","cible":"it","ex":"une décision instruite","niveau":"facile"},
  {"inf":"interdire","rad":"interd","ppFem":"interdite","cible":"it","ex":"une parole interdite","niveau":"facile"},
  {"inf":"introduire","rad":"introdu","ppFem":"introduite","cible":"it","ex":"la lettre introduite","niveau":"facile"},
  {"inf":"joindre","rad":"jo","ppFem":"jointe","cible":"int","ex":"la lettre jointe","niveau":"facile"},
  {"inf":"méfaire","rad":"méf","ppFem":"méfaite","cible":"ait","ex":"une décision méfaite","niveau":"difficile"},
  {"inf":"se méprendre","rad":"mépr","ppFem":"méprise","cible":"is","ex":"une personne méprise","niveau":"difficile","pronominal":true},
  {"inf":"oindre","rad":"o","ppFem":"ointe","cible":"int","ex":"une décision ointe","niveau":"difficile"},
  {"inf":"peindre","rad":"pe","ppFem":"peinte","cible":"int","ex":"la maison peinte","niveau":"facile"},
  {"inf":"plaindre","rad":"pla","ppFem":"plainte","cible":"int","ex":"une décision plainte","niveau":"facile"},
  {"inf":"prendre","rad":"pr","ppFem":"prise","cible":"is","ex":"une décision prise","niveau":"facile"},
  {"inf":"prescrire","rad":"prescr","ppFem":"prescrite","cible":"it","ex":"la lettre prescrite","niveau":"facile"},
  {"inf":"produire","rad":"produ","ppFem":"produite","cible":"it","ex":"une décision produite","niveau":"facile"},
  {"inf":"proscrire","rad":"proscr","ppFem":"proscrite","cible":"it","ex":"la lettre proscrite","niveau":"difficile"},
  {"inf":"reconstruire","rad":"reconstru","ppFem":"reconstruite","cible":"it","ex":"la maison reconstruite","niveau":"facile"},
  {"inf":"recuire","rad":"recu","ppFem":"recuite","cible":"it","ex":"la carotte recuite","niveau":"difficile"},
  {"inf":"redire","rad":"red","ppFem":"redite","cible":"it","ex":"une parole redite","niveau":"facile"},
  {"inf":"refaire","rad":"ref","ppFem":"refaite","cible":"ait","ex":"une décision refaite","niveau":"facile"},
  {"inf":"rejoindre","rad":"rejo","ppFem":"rejointe","cible":"int","ex":"la lettre rejointe","niveau":"facile"},
  {"inf":"renduire","rad":"rendu","ppFem":"renduite","cible":"it","ex":"la maison renduite","niveau":"difficile"},
  {"inf":"repeindre","rad":"repe","ppFem":"repeinte","cible":"int","ex":"la maison repeinte","niveau":"facile"},
  {"inf":"reproduire","rad":"reprodu","ppFem":"reproduite","cible":"it","ex":"une décision reproduite","niveau":"facile"},
  {"inf":"requérir","rad":"requ","ppFem":"requise","cible":"is","ex":"une demande requise","niveau":"difficile"},
  {"inf":"restreindre","rad":"restre","ppFem":"restreinte","cible":"int","ex":"une décision restreinte","niveau":"difficile"},
  {"inf":"retranscrire","rad":"retranscr","ppFem":"retranscrite","cible":"it","ex":"la lettre retranscrite","niveau":"difficile"},
  {"inf":"récrire","rad":"récr","ppFem":"récrite","cible":"it","ex":"la lettre récrite","niveau":"difficile"},
  {"inf":"réduire","rad":"rédu","ppFem":"réduite","cible":"it","ex":"une décision réduite","niveau":"facile"},
  {"inf":"réinscrire","rad":"réinscr","ppFem":"réinscrite","cible":"it","ex":"la lettre réinscrite","niveau":"facile"},
  {"inf":"réintroduire","rad":"réintrodu","ppFem":"réintroduite","cible":"it","ex":"la lettre réintroduite","niveau":"difficile"},
  {"inf":"réécrire","rad":"réécr","ppFem":"réécrite","cible":"it","ex":"la lettre réécrite","niveau":"facile"},
  {"inf":"s’éprendre","rad":"épr","ppFem":"éprise","cible":"is","ex":"une personne éprise","niveau":"difficile","pronominal":true},
  {"inf":"satisfaire","rad":"satisf","ppFem":"satisfaite","cible":"ait","ex":"une demande satisfaite","niveau":"facile"},
  {"inf":"souscrire","rad":"souscr","ppFem":"souscrite","cible":"it","ex":"la lettre souscrite","niveau":"difficile"},
  {"inf":"surprendre","rad":"surpr","ppFem":"surprise","cible":"is","ex":"une personne surprise","niveau":"facile"},
  {"inf":"surproduire","rad":"surprodu","ppFem":"surproduite","cible":"it","ex":"une décision surproduite","niveau":"difficile"},
  {"inf":"séduire","rad":"sédu","ppFem":"séduite","cible":"it","ex":"une personne séduite","niveau":"facile"},
  {"inf":"s’enquérir","rad":"enqu","ppFem":"enquise","cible":"is","ex":"une demande enquise","niveau":"difficile","pronominal":true},
  {"inf":"teindre","rad":"te","ppFem":"teinte","cible":"int","ex":"la maison teinte","niveau":"facile"},
  {"inf":"traduire","rad":"tradu","ppFem":"traduite","cible":"it","ex":"la lettre traduite","niveau":"facile"},
  {"inf":"transcrire","rad":"transcr","ppFem":"transcrite","cible":"it","ex":"la lettre transcrite","niveau":"difficile"},
  {"inf":"éconduire","rad":"écondu","ppFem":"éconduite","cible":"it","ex":"une personne éconduite","niveau":"difficile"},
  {"inf":"écrire","rad":"écr","ppFem":"écrite","cible":"it","ex":"la lettre écrite","niveau":"facile"},
  {"inf":"mettre","rad":"m","ppFem":"mise","cible":"is","ex":"une décision mise","niveau":"facile"},
  {"inf":"inclure","rad":"incl","ppFem":"incluse","cible":"us","ex":"une demande incluse","niveau":"facile"},
];