// Conju J'aime — Passé simple — 331 verbes — base complète
// Terminaisons A  : -ai / -as / -a / -a / -èrent
// Terminaisons I  : -is / -is / -it / -it / -irent
// Terminaisons U  : -us / -us / -ut / -ut / -urent
// Terminaisons IN : -ins / -ins / -int / -int / -inrent  (tenir/venir)
// Pronominaux : formes[] = radicaux pour [je, tu, il, on, elles]

// 331 verbes au total

// cat: "A" — verbes en -ER (118 verbes)
const verbesPS_A = [
 { inf: "aller", niv: 1, rad: "all" },
  { inf: "aboyer", niv: 2, rad: "aboy" },
  { inf: "accéder", niv: 3, rad: "accéd" },
  { inf: "acheter", niv: 2, rad: "achet" },
  { inf: "acquiescer", niv: 4, rad: "acquiesç" },
  { inf: "acquitter", niv: 4, rad: "acquitt" },
  { inf: "adhérer", niv: 3, rad: "adhér" },
  { inf: "appuyer", niv: 2, rad: "appuy" },
  { inf: "arriver", niv: 1, rad: "arriv" },
  { inf: "avouer", niv: 1, rad: "avou" },
  { inf: "balayer", niv: 2, rad: "balay" },
  { inf: "bayer", niv: 3, rad: "bay" },
  { inf: "broyer", niv: 4, rad: "broy" },
  { inf: "bégayer", niv: 2, rad: "bégay" },
  { inf: "bêler", niv: 2, rad: "bêl" },
  { inf: "cesser", niv: 2, rad: "cess" },
  { inf: "chanceler", niv: 4, rad: "chancel" },
  { inf: "chatoyer", niv: 4, rad: "chatoy" },
  { inf: "choyer", niv: 4, rad: "choy" },
  { inf: "clignoter", niv: 4, rad: "clignot" },
  { inf: "convoyer", niv: 4, rad: "convoy" },
  { inf: "coopérer", niv: 2, rad: "coopér" },
  { inf: "coïncider", niv: 4, rad: "coïncid" },
  { inf: "crocheter", niv: 3, rad: "crochet" },
  { inf: "côtoyer", niv: 3, rad: "côtoy" },
  { inf: "demander", niv: 4, rad: "demand" },
  { inf: "desserrer", niv: 3, rad: "desserr" },
  { inf: "donner", niv: 1, rad: "donn" },
  { inf: "déblayer", niv: 2, rad: "déblay" },
  { inf: "décacheter", niv: 4, rad: "décachet" },
  { inf: "déceler", niv: 3, rad: "décel" },
  { inf: "décider", niv: 1, rad: "décid" },
  { inf: "déficeler", niv: 4, rad: "déficel" },
  { inf: "défrayer", niv: 4, rad: "défray" },
  { inf: "dégeler", niv: 3, rad: "dégel" },
  { inf: "déjeuner", niv: 1, rad: "déjeun" },
  { inf: "délayer", niv: 2, rad: "délay" },
  { inf: "déléguer", niv: 4, rad: "délégu" },
  { inf: "démanteler", niv: 4, rad: "démantel" },
  { inf: "dénouer", niv: 2, rad: "dénou" },
  { inf: "déployer", niv: 4, rad: "déploy" },
  { inf: "déverser", niv: 3, rad: "dévers" },
  { inf: "dévoyer", niv: 4, rad: "dévoy" },
  { inf: "dîner", niv: 1, rad: "dîn" },
  { inf: "effrayer", niv: 2, rad: "effray" },
  { inf: "empaqueter", niv: 3, rad: "empaquet" },
  { inf: "employer", niv: 3, rad: "employ" },
  { inf: "ennuyer", niv: 2, rad: "ennuy" },
  { inf: "enrayer", niv: 3, rad: "enray" },
  { inf: "entrer", niv: 1, rad: "entr" },
  { inf: "envoyer", niv: 2, rad: "envoy" },
  { inf: "essayer", niv: 2, rad: "essay" },
  { inf: "essuyer", niv: 2, rad: "essuy" },
  { inf: "exhaler", niv: 4, rad: "exhal" },
  { inf: "écouter", niv: 1, rad: "écout" },
  { inf: "égayer", niv: 4, rad: "égay" },
  { inf: "élever", niv: 2, rad: "élev" },
  { inf: "épousseter", niv: 4, rad: "épousset" },
  { inf: "étayer", niv: 4, rad: "étay" },
  { inf: "étiqueter", niv: 4, rad: "étiquet" },
  { inf: "festoyer", niv: 4, rad: "festoy" },
  { inf: "feuilleter", niv: 3, rad: "feuillet" },
  { inf: "ficeler", niv: 3, rad: "ficel" },
  { inf: "flamboyer", niv: 4, rad: "flamboy" },
  { inf: "foudroyer", niv: 3, rad: "foudroy" },
  { inf: "fourvoyer", niv: 4, rad: "fourvoy" },
  { inf: "haleter", niv: 3, rad: "halet" },
  { inf: "harceler", niv: 4, rad: "harcel" },
  { inf: "influencer", niv: 3, rad: "influenç" },
  { inf: "intéresser", niv: 4, rad: "intéress" },
  { inf: "larmoyer", niv: 3, rad: "larmoy" },
  { inf: "louer", niv: 1, rad: "lou" },
  { inf: "louvoyer", niv: 4, rad: "louvoy" },
  { inf: "léguer", niv: 3, rad: "légu" },
  { inf: "maugréer", niv: 4, rad: "maugré" },
  { inf: "monnayer", niv: 3, rad: "monnay" },
  { inf: "nettoyer", niv: 2, rad: "nettoy" },
  { inf: "nouer", niv: 1, rad: "nou" },
  { inf: "noyer", niv: 2, rad: "noy" },
  { inf: "octroyer", niv: 3, rad: "octroy" },
  { inf: "pagayer", niv: 3, rad: "pagay" },
  { inf: "parsemer", niv: 3, rad: "parsem" },
  { inf: "payer", niv: 2, rad: "pay" },
  { inf: "ployer", niv: 3, rad: "ploy" },
  { inf: "prodiguer", niv: 4, rad: "prodigu" },
  { inf: "profiter", niv: 2, rad: "profit" },
  { inf: "projeter", niv: 3, rad: "projet" },
  { inf: "rayer", niv: 2, rad: "ray" },
  { inf: "receler", niv: 4, rad: "recel" },
  { inf: "recréer", niv: 3, rad: "recré" },
  { inf: "rectifier", niv: 4, rad: "rectifi" },
  { inf: "relayer", niv: 2, rad: "relay" },
  { inf: "reléguer", niv: 4, rad: "relégu" },
  { inf: "remblayer", niv: 4, rad: "remblay" },
  { inf: "rentrer", niv: 1, rad: "rentr" },
  { inf: "renvoyer", niv: 2, rad: "renvoy" },
  { inf: "reprocher", niv: 4, rad: "reproch" },
  { inf: "ressemeler", niv: 4, rad: "ressemel" },
  { inf: "s'arrêter", niv: 1, formes: ["m'arrêt", "t'arrêt", "s'arrêt", "s'arrêt", "s'arrêt"] },
  { inf: "se dévouer", niv: 2, formes: ["me dévou", "te dévou", "se dévou", "se dévou", "se dévou"] },
  { inf: "se frayer", niv: 4, formes: ["me fray", "te fray", "se fray", "se fray", "se fray"] },
  { inf: "secouer", niv: 1, rad: "secou" },
  { inf: "soudoyer", niv: 3, rad: "soudoy" },
  { inf: "souffler", niv: 1, rad: "souffl" },
  { inf: "soupeser", niv: 3, rad: "soupes" },
  { inf: "succéder", niv: 4, rad: "succéd" },
  { inf: "suppléer", niv: 4, rad: "supplé" },
  { inf: "surgeler", niv: 3, rad: "surgel" },
  { inf: "surpayer", niv: 2, rad: "surpay" },
  { inf: "s’apitoyer", niv: 4, formes: ["me se s’apitoy", "te se s’apitoy", "se se s’apitoy", "se se s’apitoy", "se se s’apitoy"] },
  { inf: "tapisser", niv: 3, rad: "tapiss" },
  { inf: "tatouer", niv: 2, rad: "tatou" },
  { inf: "tomber", niv: 1, rad: "tomb" },
  { inf: "tournoyer", niv: 3, rad: "tournoy" },
  { inf: "tutoyer", niv: 2, rad: "tutoy" },
  { inf: "verdoyer", niv: 3, rad: "verdoy" },
  { inf: "vouer", niv: 3, rad: "vou" },
  { inf: "vouvoyer", niv: 2, rad: "vouvoy" },
  { inf: "zézayer", niv: 4, rad: "zézay" },
];

// cat: "I" — 2e groupe + 3e en -IR/-RE/-DRE... (168 verbes)
const verbesPS_I = [
  { inf: "acquérir", niv: 4, rad: "acqu", gr:3 },
  { inf: "agir", niv: 2, rad: "ag", gr:2 },
  { inf: "applaudir", niv: 2, rad: "applaud", gr:2 },
  { inf: "apprendre", niv: 1, rad: "appr", gr:3 },
  { inf: "arrondir", niv: 2, rad: "arrond", gr:2 },
  { inf: "s'asseoir", niv: 2, formes: ["m'ass", "t'ass", "s'ass", "s'ass", "s'ass"], gr:3 },
  { inf: "astreindre", niv: 4, rad: "astreign", gr:3 },
  { inf: "atteindre", niv: 3, rad: "atteign", gr:3 },
  { inf: "attendre", niv: 3, rad: "attend", gr:3 },
  { inf: "avertir", niv: 2, rad: "avert", gr:2 },
  { inf: "battre", niv: 1, rad: "batt", gr:3 },
  { inf: "blanchir", niv: 1, rad: "blanch", gr:2 },
  { inf: "blondir", niv: 1, rad: "blond", gr:2 },
  { inf: "blêmir", niv: 1, rad: "blêm", gr:2 },
  { inf: "bondir", niv: 1, rad: "bond", gr:2 },
  { inf: "bouillir", niv: 2, rad: "bouill", gr:2 },
  { inf: "brunir", niv: 1, rad: "brun", gr:2 },
  { inf: "bâtir", niv: 1, rad: "bât", gr:2 },
  { inf: "bénir", niv: 1, rad: "bén", gr:2 },
  { inf: "ceindre", niv: 4, rad: "ceign", gr:3 },
  { inf: "choisir", niv: 1, rad: "chois", gr:2 },
  { inf: "circonscrire", niv: 4, rad: "circonscriv", gr:3 },
  { inf: "combattre", niv: 2, rad: "combatt", gr:3 },
  { inf: "comprendre", niv: 1, rad: "compr", gr:3 },
  { inf: "condescendre", niv: 4, rad: "condescend", gr:3 },
  { inf: "conduire", niv: 2, rad: "conduis", gr:3 },
  { inf: "confire", niv: 2, rad: "conf", gr:3 },
  { inf: "confondre", niv: 2, rad: "confond", gr:3 },
  { inf: "conquérir", niv: 4, rad: "conqu", gr:3 },
  { inf: "consentir", niv: 2, rad: "consent", gr:3 },
  { inf: "construire", niv: 3, rad: "construis", gr:3 },
  { inf: "contraindre", niv: 4, rad: "contraign", gr:3 },
  { inf: "contredire", niv: 1, rad: "contred", gr:3 },
  { inf: "contrefaire", niv: 3, rad: "contref", gr:3 },
  { inf: "correspondre", niv: 2, rad: "correspond", gr:3 },
  { inf: "coudre", niv: 4, rad: "cous", gr:3 },
  { inf: "craindre", niv: 3, rad: "craign", gr:3 },
  { inf: "cuire", niv: 3, rad: "cuis", gr:3 },
  { inf: "descendre", niv: 3, rad: "descend", gr:3 },
  { inf: "desservir", niv: 2, rad: "desserv", gr:3 },
  { inf: "dire", niv: 1, rad: "d", gr:3 },
  { inf: "divertir", niv: 2, rad: "divert", gr:2 },
  { inf: "dormir", niv: 1, rad: "dorm", gr:3 },
  { inf: "durcir", niv: 1, rad: "durc", gr:2 },
  { inf: "découdre", niv: 4, rad: "décous", gr:3 },
  { inf: "décrire", niv: 3, rad: "décriv", gr:3 },
  { inf: "déduire", niv: 3, rad: "déduis", gr:3 },
  { inf: "défaire", niv: 3, rad: "déf", gr:3 },
  { inf: "défendre", niv: 2, rad: "défend", gr:3 },
  { inf: "définir", niv: 1, rad: "défin", gr:2 },
  { inf: "démentir", niv: 2, rad: "dément", gr:3 },
  { inf: "démordre", niv: 2, rad: "démord", gr:3 },
  { inf: "départir", niv: 2, rad: "départ", gr:3 },
  { inf: "dépeindre", niv: 3, rad: "dépeign", gr:3 },
  { inf: "dépendre", niv: 2, rad: "dépend", gr:3 },
  { inf: "déteindre", niv: 4, rad: "déteign", gr:3 },
  { inf: "détendre", niv: 2, rad: "détend", gr:3 },
  { inf: "distendre", niv: 3, rad: "distend", gr:3 },
  { inf: "détruire", niv: 1, rad: "détruis", gr:3 },
  { inf: "embellir", niv: 1, rad: "embell", gr:2 },
  { inf: "emplir", niv: 1, rad: "empl", gr:2 },
  { inf: "enduire", niv: 3, rad: "enduis", gr:3 },
  { inf: "enfouir", niv: 2, rad: "enfou", gr:3 },
  { inf: "enfreindre", niv: 4, rad: "enfreign", gr:3 },
  { inf: "engloutir", niv: 1, rad: "englout", gr:2 },
  { inf: "engourdir", niv: 2, rad: "engourd", gr:3 },
  { inf: "enjoindre", niv: 4, rad: "enjoign", gr:3 },
  { inf: "enrichir", niv: 1, rad: "enrich", gr:2 },
  { inf: "entendre", niv: 1, rad: "entend", gr:3 },
  { inf: "entreprendre", niv: 2, rad: "entrepr", gr:3 },
  { inf: "envahir", niv: 2, rad: "envah", gr:2 },
  { inf: "faire", niv: 1, rad: "f", gr:3 },
  { inf: "feindre", niv: 4, rad: "feign", gr:3 },
  { inf: "fendre", niv: 2, rad: "fend", gr:3 },
  { inf: "fondre", niv: 2, rad: "fond", gr:3 },
  { inf: "fuir", niv: 1, rad: "fu", gr:3 },
  { inf: "geindre", niv: 4, rad: "geign", gr:3 },
  { inf: "induire", niv: 4, rad: "induis", gr:3 },
  { inf: "inscrire", niv: 3, rad: "inscriv", gr:3 },
  { inf: "instruire", niv: 3, rad: "instruis", gr:3 },
  { inf: "interdire", niv: 2, rad: "interd", gr:3 },
  { inf: "introduire", niv: 3, rad: "introduis", gr:3 },
  { inf: "joindre", niv: 4, rad: "joign", gr:3 },
  { inf: "mentir", niv: 1, rad: "ment", gr:3 },
  { inf: "mordre", niv: 1, rad: "mord", gr:3 },
  { inf: "méfaire", niv: 3, rad: "méf", gr:3 },
  { inf: "se méprendre", niv: 2, formes: ["me mépr", "te mépr", "se mépr", "se mépr", "se mépr"] , gr:3 },
  { inf: "naître", niv: 4, rad: "naqu", gr:3 },
  { inf: "oindre", niv: 4, rad: "oign", gr:3 },
  { inf: "partir", niv: 1, rad: "part", gr:3 },
  { inf: "peindre", niv: 2, rad: "peign", gr:3 },
  { inf: "pendre", niv: 1, rad: "pend", gr:3 },
  { inf: "perdre", niv: 1, rad: "perd", gr:3 },
  { inf: "plaindre", niv: 4, rad: "plaign", gr:3 },
  { inf: "pondre", niv: 3, rad: "pond", gr:3 },
  { inf: "pourfendre", niv: 3, rad: "pourfend", gr:3 },
  { inf: "prendre", niv: 1, rad: "pr", gr:3 },
  { inf: "prescrire", niv: 3, rad: "prescriv", gr:3 },
  { inf: "pressentir", niv: 2, rad: "pressent", gr:3 },
  { inf: "produire", niv: 3, rad: "produis", gr:3 },
  { inf: "proscrire", niv: 4, rad: "proscriv", gr:3 },
  { inf: "prétendre", niv: 2, rad: "prétend", gr:3 },
  { inf: "prévoir", niv: 2, rad: "prév", gr:3 },
  { inf: "reconstruire", niv: 3, rad: "recontruis", gr:3 },
  { inf: "recoudre", niv: 3, rad: "recous", gr:3 },
  { inf: "recuire", niv: 3, rad: "recuis", gr:3 },
  { inf: "redire", niv: 2, rad: "red", gr:3 },
  { inf: "se rendormir", niv: 1, formes: ["me rendorm", "te rendorm", "se rendorm", "se rendorm", "se rendorm"] , gr:3 },
  { inf: "refaire", niv: 2, rad: "ref", gr:3 },
  { inf: "rejoindre", niv: 4, rad: "rejoign", gr:3 },
  { inf: "rendre", niv: 1, rad: "rend", gr:3 },
  { inf: "renduire", niv: 3, rad: "renduis", gr:3 },
  { inf: "repartir", niv: 3, rad: "repart", gr:3 },
  { inf: "repeindre", niv: 3, rad: "repeign", gr:3 },
  { inf: "reproduire", niv: 4, rad: "reproduis", gr:3 },
  { inf: "requérir", niv: 4, rad: "requ", gr:3 },
  { inf: "ressentir", niv: 2, rad: "ressent", gr:3 },
  { inf: "resservir", niv: 2, rad: "resserv", gr:3 },
  { inf: "ressortir", niv: 2, rad: "ressort", gr:3 },
  { inf: "restreindre", niv: 4, rad: "restreign", gr:3 },
  { inf: "retranscrire", niv: 4, rad: "retranscriv", gr:3 },
  { inf: "revendre", niv: 2, rad: "revend", gr:3 },
  { inf: "revoir", niv: 1, rad: "rev", gr:3 },
  { inf: "rire", niv: 1, rad: "r", gr:3 },
  { inf: "récrire", niv: 3, rad: "récriv", gr:3 },
  { inf: "réduire", niv: 3, rad: "réduis", gr:3 },
  { inf: "réinscrire", niv: 3, rad: "réinscriv", gr:3 },
  { inf: "réintroduire", niv: 4, rad: "réintroduis", gr:3 },
  { inf: "répandre", niv: 2, rad: "répand", gr:3 },
  { inf: "répondre", niv: 1, rad: "répond", gr:3 },
  { inf: "réunir", niv: 1, rad: "réun", gr:2 },
  { inf: "réécrire", niv: 3, rad: "réécriv", gr:3 },
  { inf: "s’éprendre", niv: 3, formes: ["me se épr", "te se épr", "se se épr", "se se épr", "se se épr"] , gr:3 },
  { inf: "satisfaire", niv: 3, rad: "satisf", gr:3 },
  { inf: "se blottir", niv: 1, formes: ["me blott", "te blott", "se blott", "se blott", "se blott"] , gr:3 },
  { inf: "se morfondre", niv: 3, formes: ["me morfond", "te morfond", "se morfond", "se morfond", "se morfond"] , gr:3 },
  { inf: "se rendre", niv: 1, formes: ["me rend", "te rend", "se rend", "se rend", "se rend"] , gr:3 },
  { inf: "se repentir", niv: 2, formes: ["me repent", "te repent", "se repent", "se repent", "se repent"] , gr:3 },
  { inf: "sentir", niv: 1, rad: "sent", gr:3 },
  { inf: "servir", niv: 1, rad: "serv", gr:3 },
  { inf: "sortir", niv: 1, rad: "sort", gr:3 },
  { inf: "sourire", niv: 1, rad: "sour", gr:3 },
  { inf: "souscrire", niv: 3, rad: "souscriv", gr:3 },
  { inf: "suffire", niv: 2, rad: "suff", gr:3 },
  { inf: "suivre", niv: 2, rad: "suiv", gr:3 },
  { inf: "surprendre", niv: 2, rad: "surpr", gr:3 },
  { inf: "surproduire", niv: 4, rad: "surproduis", gr:3 },
  { inf: "suspendre", niv: 3, rad: "suspend", gr:3 },
  { inf: "séduire", niv: 3, rad: "séduis", gr:3 },
  { inf: "s’endormir", niv: 1, formes: ["me se endorm", "te se endorm", "se se endorm", "se se endorm", "se se endorm"] , gr:3 },
  { inf: "s’enfuir", niv: 1, formes: ["me se s’enfu", "te se s’enfu", "se se s’enfu", "se se s’enfu", "se se s’enfu"] , gr:3 },
  { inf: "s’enhardir", niv: 3, formes: ["me se s’enhard", "te se s’enhard", "se se s’enhard", "se se s’enhard", "se se s’enhard"] , gr:3 },
  { inf: "s’enquérir", niv: 4, formes: ["me se s’enqu", "te se s’enqu", "se se s’enqu", "se se s’enqu", "se se s’enqu"] , gr:3 },
  { inf: "teindre", niv: 4, rad: "teign", gr:3 },
  { inf: "tendre", niv: 2, rad: "tend", gr:3 },
  { inf: "tordre", niv: 2, rad: "tord", gr:3 },
  { inf: "traduire", niv: 3, rad: "traduis", gr:3 },
  { inf: "transcrire", niv: 4, rad: "transcriv", gr:3 },
  { inf: "vendre", niv: 1, rad: "vend", gr:3 },
  { inf: "voir", niv: 1, rad: "v", gr:3 },
  { inf: "éblouir", niv: 1, rad: "éblou", gr:2 },
  { inf: "éclaircir", niv: 2, rad: "éclairc", gr:2 },
  { inf: "éconduire", niv: 4, rad: "éconduis", gr:3 },
  { inf: "écrire", niv: 2, rad: "écriv", gr:3 },
  { inf: "élargir", niv: 1, rad: "élarg", gr:2 },
  { inf: "épaissir", niv: 1, rad: "épaiss", gr:2 },
  { inf: "établir", niv: 1, rad: "établ", gr:2 },
  { inf: "mettre", niv: 1, rad: "m", gr:3 },
];

// cat: "U" — 3e groupe spécial (45 verbes)
const verbesPS_U = [
  { inf: "accourir", niv: 3, rad: "accour" },
  { inf: "apercevoir", niv: 4, rad: "aperç" },
  { inf: "apparaître", niv: 4, rad: "appar" },
  { inf: "boire", niv: 3, rad: "b" },
  { inf: "comparaître", niv: 4, rad: "compar" },
  { inf: "complaire", niv: 4, rad: "compl" },
  { inf: "conclure", niv: 2, rad: "concl" },
  { inf: "concourir", niv: 3, rad: "concour" },
  { inf: "connaître", niv: 3, rad: "conn" },
  { inf: "courir", niv: 2, rad: "cour" },
  { inf: "croire", niv: 3, rad: "cr" },
  { inf: "devoir", niv: 2, rad: "d" },
  { inf: "discourir", niv: 4, rad: "discour" },
  { inf: "disparaître", niv: 3, rad: "dispar" },
  { inf: "déplaire", niv: 3, rad: "dépl" },
  { inf: "élire", niv: 3, rad: "él" },
  { inf: "réélire", niv: 3, rad: "réél" },
  { inf: "émouvoir", niv: 3, rad: "ém" },
  { inf: "promouvoir", niv: 3, rad: "prom" },
  { inf: "encourir", niv: 3, rad: "encour" },
  { inf: "lire", niv: 2, rad: "l" },
  { inf: "moudre", niv: 2, rad: "moul" },
  { inf: "méconnaître", niv: 3, rad: "méconn" },
  { inf: "paraître", niv: 3, rad: "par" },
  { inf: "parcourir", niv: 3, rad: "parcour" },
  { inf: "plaire", niv: 3, rad: "pl" },
  { inf: "pourvoir", niv: 3, rad: "pourv" },
  { inf: "pouvoir", niv: 2, rad: "p" },
  { inf: "prévaloir", niv: 3, rad: "préval" },
  { inf: "reconnaître", niv: 3, rad: "reconn" },
  { inf: "recourir", niv: 3, rad: "recour" },
  { inf: "relire", niv: 2, rad: "rel" },
  { inf: "revivre", niv: 3, rad: "revéc" },
  { inf: "réapparaître", niv: 3, rad: "réappar" },
  { inf: "résoudre", niv: 4, rad: "résol" },
  { inf: "savoir", niv: 2, rad: "s" },
  { inf: "se taire", niv: 3, formes: ["me t", "te t", "se t", "se t", "se t"] },
  { inf: "secourir", niv: 3, rad: "secour" },
  { inf: "survivre", niv: 3, rad: "survéc" },
  { inf: "transparaître", niv: 4, rad: "transpar" },
  { inf: "valoir", niv: 3, rad: "val" },
  { inf: "vivre", niv: 3, rad: "véc" },
  { inf: "vouloir", niv: 3, rad: "voul" },
  { inf: "être", niv: 3, rad: "f" },
  { inf: "avoir", niv: 3, rad: "e" },
];

const verbesPS_IVenir = [];
const verbesPS = [...verbesPS_A, ...verbesPS_I, ...verbesPS_IVenir, ...verbesPS_U];

// Aliases pour compatibilité avec le code des jeux
const verbesPSpetit_A = verbesPS_A;
const verbesPSpetit_I = verbesPS_I;
const verbesPSpetit_U = verbesPS_U;
const verbesPSpetit_IVenir = verbesPS_IVenir;
const verbesPSpetit = verbesPS;
