const verbesSubjPresent = [
  // REGULIER
//GROUPE 1 //
  { infinitif: "accentuer", niveau: 3, radical: "accentu" },
  { infinitif: "acheter", niveau: 1, radical: "achèt", radNousVous: "achet" },
  { infinitif: "amplifier", niveau: 3, radical: "amplifi" },
  { infinitif: "apprécier", niveau: 3, radical: "appréci" },
  { infinitif: "associer", niveau: 3, radical: "associ" },
  { infinitif: "attribuer", niveau: 3, radical: "attribu" },
  { infinitif: "atténuer", niveau: 3, radical: "atténu" },
  { infinitif: "avouer", niveau: 2, radical: "avou" },
  { infinitif: "balbutier", niveau: 3, radical: "balbuti" },
  { infinitif: "bénéficier", niveau: 4, radical: "bénéfici" },
  { infinitif: "certifier", niveau: 3, radical: "certifi" },
  { infinitif: "clarifier", niveau: 2, radical: "clarifi" },
  { infinitif: "colorier", niveau: 2, radical: "colori" },
  { infinitif: "appuyer", niveau: 2, radical: "appui", radNousVous: "appuy" },
  { infinitif: "balayer", niveau: 2, radical: "balai", radNousVous: "balay" },
  { infinitif: "bayer", niveau: 4, radical: "bai", radNousVous: "bay" },
  { infinitif: "broyer", niveau: 4, radical: "broi", radNousVous: "broy" },
  { infinitif: "bégayer", niveau: 2, radical: "bégai", radNousVous: "bégay" },
  { infinitif: "chatoyer", niveau: 4, radical: "chatoi", radNousVous: "chatoy" },
  { infinitif: "choyer", niveau: 4, radical: "choi", radNousVous: "choy" },
  { infinitif: "complexifier", niveau: 4, radical: "complexifi" },
  { infinitif: "concilier", niveau: 4, radical: "concili" },
  { infinitif: "contrarier", niveau: 3, radical: "contrari" },
  { infinitif: "convier", niveau: 3, radical: "convi" },
  { infinitif: "crier", niveau: 1, radical: "cri" },
  { infinitif: "côtoyer", niveau: 3, radical: "côtoi", radNousVous: "côtoy" },
  { infinitif: "différencier", niveau: 4, radical: "différenci" },
  { infinitif: "diluer", niveau: 3, radical: "dilu" },
  { infinitif: "distribuer", niveau: 3, radical: "distribu" },
  { infinitif: "déblayer", niveau: 3, radical: "déblai", radNousVous: "déblay" },
  { infinitif: "décrier", niveau: 3, radical: "décri" },
  { infinitif: "défier", niveau: 3, radical: "défi" },
  { infinitif: "défrayer", niveau: 3, radical: "défrai", radNousVous: "défray" },
  { infinitif: "délier", niveau: 2, radical: "déli" },
  { infinitif: "dénier", niveau: 3, radical: "déni" },
  { infinitif: "dénouer", niveau: 3, radical: "dénou" },
  { infinitif: "déplier", niveau: 1, radical: "dépli" },
  { infinitif: "déployer", niveau: 3, radical: "déploi", radNousVous: "déploy" },
  { infinitif: "effectuer", niveau: 2, radical: "effectu" },
  { infinitif: "effrayer", niveau: 2, radical: "effrai", radNousVous: "effray" },
  { infinitif: "employer", niveau: 3, radical: "emploi", radNousVous: "employ" },
  { infinitif: "ennuyer", niveau: 2, radical: "ennui", radNousVous: "ennuy" },
  { infinitif: "enrayer", niveau: 3, radical: "enrai", radNousVous: "enray" },
  { infinitif: "envier", niveau: 2, radical: "envi" },
  { infinitif: "envoyer", niveau: 2, radical: "envoi", radNousVous: "envoy" },
  { infinitif: "essayer", niveau: 2, radical: "essai", radNousVous: "essay" },
  { infinitif: "essuyer", niveau: 2, radical: "essui", radNousVous: "essuy" },
  { infinitif: "expédier", niveau: 3, radical: "expédi" },
  { infinitif: "éberluer", niveau: 4, radical: "éberlu" },
  { infinitif: "égayer", niveau: 2, radical: "égai", radNousVous: "égay" },
  { infinitif: "épier", niveau: 1, radical: "épi" },
  { infinitif: "étayer", niveau: 3, radical: "étai", radNousVous: "étay" },
{ infinitif: "éternuer", niveau: 2, radical: "éternu" },
  { infinitif: "étudier", niveau: 1, radical: "étudi" },
  { infinitif: "évacuer", niveau: 2, radical: "évacu" },
  { infinitif: "évaluer", niveau: 3, radical: "évalu" },
  { infinitif: "évoluer", niveau: 3, radical: "évolu" },
  { infinitif: "festoyer", niveau: 4, radical: "festoi", radNousVous: "festoy" },
  { infinitif: "foudroyer", niveau: 3, radical: "foudroi", radNousVous: "foudroy" },
  { infinitif: "habituer", niveau: 2, radical: "habitu" },
  { infinitif: "identifier", niveau: 2, radical: "identifi" },
  { infinitif: "influer", niveau: 4, radical: "influ" },
  { infinitif: "initier", niveau: 3, radical: "initi" },
  { infinitif: "insinuer", niveau: 4, radical: "insinu" },
  { infinitif: "intensifier", niveau: 4, radical: "intensifi" },
  { infinitif: "justifier", niveau: 3, radical: "justifi" },
  { infinitif: "jouer", niveau: 1, radical: "jou" },
  { infinitif: "licencier", niveau: 3, radical: "licenci" },
  { infinitif: "lier", niveau: 1, radical: "li" },
  { infinitif: "louer", niveau: 1, radical: "lou" },
  { infinitif: "louvoyer", niveau: 4, radical: "louvoi", radNousVous: "louvoy" },
  { infinitif: "manier", niveau: 2, radical: "mani" },
  { infinitif: "marier", niveau: 1, radical: "mari" },
  { infinitif: "maugréer", niveau: 4, radical: "maugré" },
  { infinitif: "mendier", niveau: 2, radical: "mendi" },
  { infinitif: "modifier", niveau: 3, radical: "modifi" },
  { infinitif: "monnayer", niveau: 3, radical: "monnai", radNousVous: "monnay" },
  { infinitif: "muer", niveau: 4, radical: "mu" },
  { infinitif: "multiplier", niveau: 3, radical: "multipli" },
  { infinitif: "nettoyer", niveau: 2, radical: "nettoi", radNousVous: "nettoy" },
  { infinitif: "nier", niveau: 3, radical: "ni" },
  { infinitif: "notifier", niveau: 3, radical: "notifi" },
  { infinitif: "nouer", niveau: 1, radical: "nou" },
  { infinitif: "noyer", niveau: 3, radical: "noi", radNousVous: "noy" },
  { infinitif: "négocier", niveau: 2, radical: "négoci" },
  { infinitif: "octroyer", niveau: 4, radical: "octroi", radNousVous: "octroy" },
  { infinitif: "officier", niveau: 4, radical: "offici" },
  { infinitif: "oublier", niveau: 1, radical: "oubli" },
  { infinitif: "pagayer", niveau: 2, radical: "pagai", radNousVous: "pagay" },
  { infinitif: "parier", niveau: 2, radical: "pari" },
  { infinitif: "payer", niveau: 2, radical: "pai", radNousVous: "pay" },
{ infinitif: "photographier", niveau: 3, radical: "photographi" },
  { infinitif: "planifier", niveau: 3, radical: "planifi" },
  { infinitif: "plier", niveau: 1, radical: "pli" },
  { infinitif: "ployer", niveau: 3, radical: "ploi", radNousVous: "ploy" },
  { infinitif: "polluer", niveau: 2, radical: "pollu" },
  { infinitif: "privilégier", niveau: 4, radical: "privilégi" },
  { infinitif: "publier", niveau: 2, radical: "publi" },
  { infinitif: "qualifier", niveau: 3, radical: "qualifi" },
  { infinitif: "rallier", niveau: 2, radical: "ralli" },
  { infinitif: "rapatrier", niveau: 3, radical: "rapatri" },
  { infinitif: "se rassasier", niveau: 3, radical: "rassasi", pronominal: true },
  { infinitif: "rayer", niveau: 2, radical: "rai", radNousVous: "ray" },
  { infinitif: "recopier", niveau: 1, radical: "recopi" },
  { infinitif: "recréer", niveau: 3, radical: "recré" },
  { infinitif: "rectifier", niveau: 3, radical: "rectifi" },
  { infinitif: "relayer", niveau: 3, radical: "relai", radNousVous: "relay" },
  { infinitif: "relier", niveau: 2, radical: "reli" },
  { infinitif: "remblayer", niveau: 4, radical: "remblai", radNousVous: "remblay" },
  { infinitif: "remercier", niveau: 2, radical: "remerci" },
  { infinitif: "remuer", niveau: 1, radical: "remu" },
  { infinitif: "remédier", niveau: 3, radical: "remédi" },
  { infinitif: "renier", niveau: 3, radical: "reni" },
  { infinitif: "renvoyer", niveau: 2, radical: "renvoi", radNousVous: "renvoy" },
  { infinitif: "replier", niveau: 2, radical: "repli" },
  { infinitif: "restituer", niveau: 4, radical: "restitu" },
  { infinitif: "ruer", niveau: 2, radical: "ru" },
{ infinitif: "réconcilier", niveau: 4, radical: "réconcili" },
  { infinitif: "répertorier", niveau: 4, radical: "répertori" },
  { infinitif: "résilier", niveau: 4, radical: "résili" },
  { infinitif: "sacrifier", niveau: 3, radical: "sacrifi" },
  { infinitif: "saluer", niveau: 1, radical: "salu" },
  { infinitif: "scier", niveau: 2, radical: "sci" },
  { infinitif: "se bonifier", niveau: 3, radical: "bonifi", pronominal: true },
  { infinitif: "se dévouer", niveau: 3, radical: "dévou", pronominal: true },
  { infinitif: "se méfier", niveau: 2, radical: "méfi", pronominal: true },
  { infinitif: "se réfugier", niveau: 3, radical: "réfugi", pronominal: true },
  { infinitif: "se soucier", niveau: 2, radical: "souci", pronominal: true },
  { infinitif: "secouer", niveau: 1, radical: "secou" },
  { infinitif: "signifier", niveau: 2, radical: "signifi" },
  { infinitif: "simplifier", niveau: 2, radical: "simplifi" },
  { infinitif: "situer", niveau: 1, radical: "situ" },
  { infinitif: "skier", niveau: 1, radical: "ski" },
  { infinitif: "soudoyer", niveau: 4, radical: "soudoi", radNousVous: "soudoy" },
  { infinitif: "spécifier", niveau: 3, radical: "spécifi" },
  { infinitif: "stupéfier", niveau: 4, radical: "stupéfi" },
  { infinitif: "substituer", niveau: 4, radical: "substitu" },
  { infinitif: "supplier", niveau: 2, radical: "suppli" },
  { infinitif: "suppléer", niveau: 4, radical: "supplé" },
  { infinitif: "surpayer", niveau: 3, radical: "surpai", radNousVous: "surpay" },
  { infinitif: "s'apitoyer", niveau: 4, radical: "apitoi", radNousVous: "apitoy", pronominal: true },
  { infinitif: "s'approprier", niveau: 4, radical: "appropri", pronominal: true },
  { infinitif: "s'extasier", niveau: 4, radical: "extasi", pronominal: true },
  { infinitif: "s'écrier", niveau: 1, radical: "écri", pronominal: true },
  { infinitif: "trier", niveau: 1, radical: "tri" },
  { infinitif: "tutoyer", niveau: 3, radical: "tutoi", radNousVous: "tutoy" },
  { infinitif: "varier", niveau: 2, radical: "vari" },
  { infinitif: "vouer", niveau: 3, radical: "vou" },
  { infinitif: "vouvoyer", niveau: 3, radical: "vouvoi", radNousVous: "vouvoy" },
  { infinitif: "vérifier", niveau: 1, radical: "vérifi" },
 { infinitif: "se tatouer", niveau: 2, radical: "tatou", pronominal: true },

// HOMOPHONES //
{ infinitif: "concourir", niveau: 3, radical: "concour" },
  { infinitif: "courir", niveau: 1, radical: "cour" },
  { infinitif: "parcourir", niveau: 3, radical: "parcour" },
  { infinitif: "recourir", niveau: 3, radical: "recour" },
  { infinitif: "secourir", niveau: 2, radical: "secour" },
 { infinitif: "conquérir", niveau: 4, radical: "conquièr", radNousVous: "conquér" },
 { infinitif: "fuir", niveau: 1, radical: "fui", radNousVous: "fuy" },
{ infinitif: "sourire", niveau: 1, radical: "souri" },
 { infinitif: "revoir", niveau: 1, radical: "revoi", radNousVous: "revoy" },
  { infinitif: "requérir", niveau: 4, radical: "requièr", radNousVous: "requér" },
 { infinitif: "prévoir", niveau: 2, radical: "prévoi", radNousVous: "prévoy" },
  { infinitif: "rire", niveau: 1, radical: "ri" },
  { infinitif: "s'enfuir", niveau: 1, radical: "enfui", radNousVous: "enfuy", pronominal: true },
  { infinitif: "s'enquérir", niveau: 4, radical: "enquièr", radNousVous: "enquér", pronominal: true },
  { infinitif: "voir", niveau: 1, radical: "voi" },
{ infinitif: "croire", niveau: 1, radical: "croi", radNousVous: "croy" },
 { infinitif: "acquérir", niveau: 3, radical: "acquièr", radNousVous: "acquér" },
  { infinitif: "accueillir", niveau: 2, radical: "accueill", radNousVous: "accueil" },
  { infinitif: "mourir", niveau: 1, radical: "meur", radNousVous: "mour" },


// VERBES IRREGULIERS //
// GROUPE 2 //
  { infinitif: "finir", niveau: 1, radical: "finiss" },
  { infinitif: "choisir", niveau: 1, radical: "choisiss" },
  { infinitif: "grandir", niveau: 1, radical: "grandiss" },
  { infinitif: "réussir", niveau: 1, radical: "réussiss" },
  { infinitif: "remplir", niveau: 1, radical: "rempliss" },
  { infinitif: "obéir", niveau: 1, radical: "obéiss" },
  { infinitif: "punir", niveau: 1, radical: "puniss" },
  { infinitif: "agir", niveau: 1, radical: "agiss" },
  { infinitif: "bâtir", niveau: 1, radical: "bâtiss" },
  { infinitif: "grossir", niveau: 1, radical: "grossiss" },
  { infinitif: "maigrir", niveau: 1, radical: "maigriss" },
  { infinitif: "jaunir", niveau: 1, radical: "jauniss" },
  { infinitif: "rougir", niveau: 1, radical: "rougiss" },
  { infinitif: "blanchir", niveau: 1, radical: "blanchiss" },
  { infinitif: "noircir", niveau: 1, radical: "noirciss" },
  { infinitif: "pâlir", niveau: 1, radical: "pâliss" },
  { infinitif: "salir", niveau: 1, radical: "saliss" },
  { infinitif: "guérir", niveau: 1, radical: "guériss" },
  { infinitif: "nourrir", niveau: 1, radical: "nourriss" },
  { infinitif: "applaudir", niveau: 1, radical: "applaudiss" },
  { infinitif: "réfléchir", niveau: 2, radical: "réfléchiss" },
  { infinitif: "établir", niveau: 2, radical: "établiss" },
  { infinitif: "réagir", niveau: 2, radical: "réagiss" },
  { infinitif: "avertir", niveau: 2, radical: "avertiss" },
  { infinitif: "bondir", niveau: 2, radical: "bondiss" },
  { infinitif: "franchir", niveau: 2, radical: "franchiss" },
  { infinitif: "fournir", niveau: 2, radical: "fourniss" },
  { infinitif: "vieillir", niveau: 2, radical: "vieilliss" },
  { infinitif: "réunir", niveau: 2, radical: "réuniss" },
  { infinitif: "fleurir", niveau: 2, radical: "fleuriss" },
  { infinitif: "rugir", niveau: 2, radical: "rugiss" },
  { infinitif: "saisir", niveau: 2, radical: "saisiss" },
  { infinitif: "trahir", niveau: 2, radical: "trahiss" },
  { infinitif: "divertir", niveau: 3, radical: "divertiss" },
  { infinitif: "durcir", niveau: 2, radical: "durciss" },
  { infinitif: "élargir", niveau: 2, radical: "élargiss" },
  { infinitif: "enrichir", niveau: 2, radical: "enrichiss" },
  { infinitif: "envahir", niveau: 2, radical: "envahiss" },
  { infinitif: "gémir", niveau: 2, radical: "gémiss" },
  { infinitif: "aboutir", niveau: 3, radical: "aboutiss" },
  { infinitif: "accomplir", niveau: 3, radical: "accompliss" },
  { infinitif: "adoucir", niveau: 3, radical: "adouciss" },
  { infinitif: "agrandir", niveau: 3, radical: "agrandiss" },
  { infinitif: "anéantir", niveau: 3, radical: "anéantiss" },
  { infinitif: "approfondir", niveau: 3, radical: "approfondiss" },
  { infinitif: "arrondir", niveau: 3, radical: "arrondiss" },
  { infinitif: "atterrir", niveau: 3, radical: "atterriss" },
  { infinitif: "convertir", niveau: 3, radical: "convertiss" },
  { infinitif: "définir", niveau: 3, radical: "définiss" },
  { infinitif: "démolir", niveau: 3, radical: "démoliss" },
  { infinitif: "désobéir", niveau: 3, radical: "désobéiss" },
  { infinitif: "éblouir", niveau: 3, radical: "éblouiss" },
  { infinitif: "frémir", niveau: 3, radical: "frémiss" },
  { infinitif: "mûrir", niveau: 3, radical: "mûriss" },
  { infinitif: "raccourcir", niveau: 3, radical: "raccourciss" },
  { infinitif: "ralentir", niveau: 3, radical: "ralentiss" },
  { infinitif: "refroidir", niveau: 3, radical: "refroidiss" },
{ infinitif: "se réjouir", niveau: 3, radical: "réjouiss", pronominal: true },
  { infinitif: "rétablir", niveau: 3, radical: "rétabliss" },
  { infinitif: "rétrécir", niveau: 3, radical: "rétréciss" },
  { infinitif: "rôtir", niveau: 3, radical: "rôtiss" },
  { infinitif: "subir", niveau: 3, radical: "subiss" },
  { infinitif: "surgir", niveau: 3, radical: "surgiss" },
  { infinitif: "abolir", niveau: 4, radical: "aboliss" },
  { infinitif: "alunir", niveau: 4, radical: "aluniss" },
  { infinitif: "amincir", niveau: 4, radical: "aminciss" },
  { infinitif: "amortir", niveau: 4, radical: "amortiss" },
  { infinitif: "aplanir", niveau: 4, radical: "aplaniss" },
  { infinitif: "assombrir", niveau: 4, radical: "assombriss" },
  { infinitif: "assortir", niveau: 4, radical: "assortiss" },
 { infinitif: "s'assoupir", niveau: 4, radical: "assoupiss", pronominal: true },
  { infinitif: "attendrir", niveau: 4, radical: "attendriss" },
  { infinitif: "compatir", niveau: 4, radical: "compatiss" },
  { infinitif: "dépérir", niveau: 4, radical: "dépériss" },
  { infinitif: "embellir", niveau: 4, radical: "embelliss" },
  { infinitif: "engloutir", niveau: 4, radical: "engloutiss" },
  { infinitif: "engourdir", niveau: 4, radical: "engourdiss" },
  { infinitif: "enlaidir", niveau: 4, radical: "enlaidiss" },
  { infinitif: "ennoblir", niveau: 4, radical: "ennobliss" },
  { infinitif: "épaissir", niveau: 4, radical: "épaississ" },
  { infinitif: "épanouir", niveau: 4, radical: "épanouiss" },
  { infinitif: "faiblir", niveau: 4, radical: "faibliss" },
  { infinitif: "gravir", niveau: 4, radical: "graviss" },
  { infinitif: "hennir", niveau: 4, radical: "henniss", hAspire: true },
  { infinitif: "investir", niveau: 4, radical: "investiss" },
  { infinitif: "jaillir", niveau: 4, radical: "jailliss" },

//GROUPE 3 //
// GROUPE 3 — verbes en -DRE
  { infinitif: "apprendre", niveau: 2, radical: "apprenn", radicalPluriel: "appren" },
  { infinitif: "attendre", niveau: 2, radical: "attend" },
  { infinitif: "s'attendre", niveau: 3, radical: "attend", pronominal: true },
  { infinitif: "comprendre", niveau: 2, radical: "comprenn", radicalPluriel: "compren" },
  { infinitif: "se comprendre", niveau: 3, radical: "comprenn", radicalPluriel: "compren", pronominal: true },
  { infinitif: "condescendre", niveau: 4, radical: "condescend" },
  { infinitif: "confondre", niveau: 3, radical: "confond" },
  { infinitif: "se confondre", niveau: 4, radical: "confond", pronominal: true },
  { infinitif: "correspondre", niveau: 3, radical: "correspond" },
  { infinitif: "se correspondre", niveau: 4, radical: "correspond", pronominal: true },
  { infinitif: "coudre", niveau: 1, radical: "cous" },
  { infinitif: "découdre", niveau: 3, radical: "décous" },
  { infinitif: "se découdre", niveau: 4, radical: "décous", pronominal: true },
  { infinitif: "défendre", niveau: 2, radical: "défend" },
  { infinitif: "se défendre", niveau: 3, radical: "défend", pronominal: true },
  { infinitif: "démordre", niveau: 4, radical: "démord" },
  { infinitif: "désapprendre", niveau: 4, radical: "désapprenn", radicalPluriel: "désappren" },
  { infinitif: "descendre", niveau: 2, radical: "descend" },
  { infinitif: "détendre", niveau: 2, radical: "détend" },
  { infinitif: "se détendre", niveau: 3, radical: "détend", pronominal: true },
  { infinitif: "détordre", niveau: 4, radical: "détord" },
  { infinitif: "distendre", niveau: 3, radical: "distend" },
  { infinitif: "entendre", niveau: 1, radical: "entend" },
  { infinitif: "s'entendre", niveau: 2, radical: "entend", pronominal: true },
  { infinitif: "entreprendre", niveau: 2, radical: "entreprenn", radicalPluriel: "entrepren" },
  { infinitif: "épandre", niveau: 3, radical: "épand" },
  { infinitif: "s'éprendre", niveau: 3, radical: "éprenn", radicalPluriel: "épren", pronominal: true },
  { infinitif: "étendre", niveau: 1, radical: "étend" },
  { infinitif: "s'étendre", niveau: 3, radical: "étend", pronominal: true },
  { infinitif: "fendre", niveau: 1, radical: "fend" },
  { infinitif: "se fendre", niveau: 3, radical: "fend", pronominal: true },
  { infinitif: "fondre", niveau: 1, radical: "fond" },
  { infinitif: "se fondre", niveau: 3, radical: "fond", pronominal: true },
  { infinitif: "se méprendre", niveau: 4, radical: "méprenn", radicalPluriel: "mépren", pronominal: true },
  { infinitif: "mordre", niveau: 1, radical: "mord" },
  { infinitif: "se mordre", niveau: 3, radical: "mord", pronominal: true },
  { infinitif: "se morfondre", niveau: 4, radical: "morfond", pronominal: true },
  { infinitif: "moudre", niveau: 1, radical: "moul" },
  { infinitif: "pendre", niveau: 1, radical: "pend" },
  { infinitif: "perdre", niveau: 1, radical: "perd" },
  { infinitif: "se perdre", niveau: 3, radical: "perd", pronominal: true },
  { infinitif: "pondre", niveau: 1, radical: "pond" },
  { infinitif: "pourfendre", niveau: 3, radical: "pourfend" },
  { infinitif: "prendre", niveau: 1, radical: "prenn", radicalPluriel: "pren" },
  { infinitif: "prétendre", niveau: 2, radical: "prétend" },
  { infinitif: "réapprendre", niveau: 4, radical: "réapprenn", radicalPluriel: "réappren" },
  { infinitif: "recoudre", niveau: 2, radical: "recous" },
  { infinitif: "redescendre", niveau: 4, radical: "redescend" },
  { infinitif: "réentendre", niveau: 4, radical: "réentend" },
  { infinitif: "refondre", niveau: 3, radical: "refond" },
  { infinitif: "rendre", niveau: 1, radical: "rend" },
  { infinitif: "se rendre", niveau: 2, radical: "rend", pronominal: true },
  { infinitif: "répandre", niveau: 1, radical: "répand" },
  { infinitif: "répondre", niveau: 1, radical: "répond" },
  { infinitif: "se répondre", niveau: 3, radical: "répond", pronominal: true },
  { infinitif: "reprendre", niveau: 1, radical: "reprenn", radicalPluriel: "repren" },
  { infinitif: "se reprendre", niveau: 3, radical: "reprenn", radicalPluriel: "repren", pronominal: true },
  { infinitif: "retendre", niveau: 2, radical: "retend" },
  { infinitif: "retondre", niveau: 4, radical: "retond" },
  { infinitif: "revendre", niveau: 1, radical: "revend" },
  { infinitif: "sous-entendre", niveau: 4, radical: "sous-entend" },
  { infinitif: "sous-tendre", niveau: 4, radical: "sous-tend" },
  { infinitif: "surprendre", niveau: 2, radical: "surprenn", radicalPluriel: "surpren" },
  { infinitif: "se surprendre", niveau: 3, radical: "surprenn", radicalPluriel: "surpren", pronominal: true },
  { infinitif: "suspendre", niveau: 2, radical: "suspend" },
  { infinitif: "tendre", niveau: 1, radical: "tend" },
  { infinitif: "se tendre", niveau: 3, radical: "tend", pronominal: true },
  { infinitif: "tondre", niveau: 1, radical: "tond" },
  { infinitif: "tordre", niveau: 1, radical: "tord" },
  { infinitif: "vendre", niveau: 1, radical: "vend" },


// GROUPE 3 — verbes en -TTRE
  { infinitif: "admettre", niveau: 2, radical: "admett" },
  { infinitif: "battre", niveau: 1, radical: "batt" },
  { infinitif: "se battre", niveau: 3, radical: "batt", pronominal: true },
  { infinitif: "combattre", niveau: 2, radical: "combatt" },
  { infinitif: "commettre", niveau: 2, radical: "commett" },
  { infinitif: "compromettre", niveau: 4, radical: "compromett" },
  { infinitif: "se compromettre", niveau: 4, radical: "compromett", pronominal: true },
  { infinitif: "débattre", niveau: 2, radical: "débatt" },
  { infinitif: "se débattre", niveau: 3, radical: "débatt", pronominal: true },
  { infinitif: "démettre", niveau: 2, radical: "démett" },
  { infinitif: "se démettre", niveau: 3, radical: "démett", pronominal: true },
  { infinitif: "émettre", niveau: 1, radical: "émett" },
  { infinitif: "mettre", niveau: 1, radical: "mett" },
  { infinitif: "se mettre", niveau: 3, radical: "mett", pronominal: true },
  { infinitif: "omettre", niveau: 1, radical: "omett" },
  { infinitif: "permettre", niveau: 2, radical: "permett" },
  { infinitif: "se permettre", niveau: 3, radical: "permett", pronominal: true },
  { infinitif: "promettre", niveau: 1, radical: "promett" },
  { infinitif: "se promettre", niveau: 3, radical: "promett", pronominal: true },
  { infinitif: "rabattre", niveau: 2, radical: "rabatt" },
  { infinitif: "se rabattre", niveau: 3, radical: "rabatt", pronominal: true },
  { infinitif: "réadmettre", niveau: 4, radical: "réadmett" },
  { infinitif: "remettre", niveau: 2, radical: "remett" },
  { infinitif: "se remettre", niveau: 3, radical: "remett", pronominal: true },
  { infinitif: "retransmettre", niveau: 4, radical: "retransmett" },
  { infinitif: "soumettre", niveau: 1, radical: "soumett" },
  { infinitif: "se soumettre", niveau: 3, radical: "soumett", pronominal: true },
  { infinitif: "télétransmettre", niveau: 4, radical: "télétransmett" },
  { infinitif: "transmettre", niveau: 2, radical: "transmett" },

//VENIR et TENIR 
{ infinitif: "advenir", niveau: 4, radical: "advienn", radNousVous: "adven" },
  { infinitif: "circonvenir", niveau: 4, radical: "convienn", radNousVous: "conven" },
  { infinitif: "contenir", niveau: 2, radical: "contienn", radNousVous: "conten" },
  { infinitif: "contrevenir", niveau: 4, radical: "contrevienn", radNousVous: "contreven" },
  { infinitif: "convenir", niveau: 3, radical: "convienn", radNousVous: "conven" },
  { infinitif: "devenir", niveau: 2, radical: "devienn", radNousVous: "deven" },
  { infinitif: "disconvenir", niveau: 4, radical: "disconvienn", radNousVous: "disconven" },
  { infinitif: "détenir", niveau: 2, radical: "détienn", radNousVous: "déten" },
  { infinitif: "maintenir", niveau: 3, radical: "maintienn", radNousVous: "mainten" },
  { infinitif: "parvenir", niveau: 3, radical: "parvienn", radNousVous: "parven" },
  { infinitif: "prévenir", niveau: 2, radical: "prévienn", radNousVous: "preven" },
  { infinitif: "provenir", niveau: 3, radical: "provienn", radNousVous: "proven" },
  { infinitif: "redevenir", niveau: 3, radical: "redevienn", radNousVous: "redeven" },
  { infinitif: "retenir", niveau: 2, radical: "retienn", radNousVous: "reten" },
  { infinitif: "revenir", niveau: 2, radical: "revienn", radNousVous: "reven" },
  { infinitif: "se souvenir", niveau: 3, radical: "souvienn", radNousVous: "souven", pronominal: true },
  { infinitif: "s'abstenir", niveau: 3, radical: "abstienn", radNousVous: "absten", pronominal: true },
  { infinitif: "soutenir", niveau: 3, radical: "soutienn", radNousVous: "souten" },
  { infinitif: "subvenir", niveau: 4, radical: "subvienn", radNousVous: "subven" },
  { infinitif: "survenir", niveau: 3, radical: "survienn", radNousVous: "surven" },
  { infinitif: "tenir", niveau: 1, radical: "tienn", radNousVous: "ten" },
  { infinitif: "venir", niveau: 1, radical: "vienn", radNousVous: "ven" },

//VERBES en INDRE
{ infinitif: "ceindre", niveau: 4, radical: "ceign" },
  { infinitif: "contraindre", niveau: 4, radical: "contraign" },
  { infinitif: "craindre", niveau: 3, radical: "craign" },
  { infinitif: "dépeindre", niveau: 4, radical: "dépeign" },
  { infinitif: "déteindre", niveau: 3, radical: "déteign" },
  { infinitif: "feindre", niveau: 4, radical: "feign" },
  { infinitif: "geindre", niveau: 4, radical: "geign" },
  { infinitif: "joindre", niveau: 4, radical: "joign" },
  { infinitif: "peindre", niveau: 3, radical: "peign" },
  { infinitif: "plaindre", niveau: 3, radical: "plaign" },
  { infinitif: "rejoindre", niveau: 3, radical: "rejoign" },
  { infinitif: "repeindre", niveau: 3, radical: "repeign" },
  { infinitif: "restreindre", niveau: 4, radical: "restreign" },
  { infinitif: "teindre", niveau: 4, radical: "teign" },

// LES AUTRES
{ infinitif: "contrefaire", niveau: 3, radical: "contrefass" },
  { infinitif: "défaire", niveau: 2, radical: "défass" },
  { infinitif: "faire", niveau: 2, radical: "fass" },
  { infinitif: "méfaire", niveau: 3, radical: "méfass" },
  { infinitif: "refaire", niveau: 3, radical: "refass" },
  { infinitif: "satisfaire", niveau: 3, radical: "satisfass" },
  { infinitif: "comparaître", niveau: 3, radical: "comparaiss" },
  { infinitif: "conduire", niveau: 1, radical: "conduis" },
  { infinitif: "confire", niveau: 3, radical: "confis" },
  { infinitif: "connaître", niveau: 2, radical: "connaiss" },
  { infinitif: "consentir", niveau: 3, radical: "consent" },
  { infinitif: "construire", niveau: 2, radical: "construis" },
  { infinitif: "contredire", niveau: 3, radical: "contredis" },
  { infinitif: "cuire", niveau: 3, radical: "cuis" },
  { infinitif: "desservir", niveau: 3, radical: "desserv" },
  { infinitif: "devoir", niveau: 1, radical: "doiv", radNousVous: "dev" },
  { infinitif: "dire", niveau: 1, radical: "dis" },
  { infinitif: "disparaître", niveau: 3, radical: "disparaiss" },
  { infinitif: "décrire", niveau: 1, radical: "décriv" },
  { infinitif: "déduire", niveau: 3, radical: "déduis" },
  { infinitif: "démentir", niveau: 3, radical: "dément" },
  { infinitif: "détruire", niveau: 2, radical: "détruis" },
  { infinitif: "luire", niveau: 3, radical: "luis" },
  { infinitif: "mentir", niveau: 2, radical: "ment" },
  { infinitif: "mouvoir", niveau: 4, radical: "meuv", radNousVous: "mouv" },
  { infinitif: "méconnaître", niveau: 4, radical: "méconnaiss" },
  { infinitif: "naître", niveau: 3, radical: "naiss" },
  { infinitif: "nuire", niveau: 4, radical: "nuis" },
  { infinitif: "paraître", niveau: 3, radical: "paraiss" },
  { infinitif: "plaire", niveau: 2, radical: "plais" },
  { infinitif: "déplaire", niveau: 2, radical: "déplais" },
  { infinitif: "complaire", niveau: 2, radical: "complais" },
  { infinitif: "prescrire", niveau: 3, radical: "prescriv" },
  { infinitif: "pressentir", niveau: 3, radical: "pressent" },
  { infinitif: "produire", niveau: 3, radical: "produis" },
  { infinitif: "promouvoir", niveau: 4, radical: "promeuv", radNousVous: "promouv" },
  { infinitif: "proscrire", niveau: 4, radical: "proscriv" },
  { infinitif: "reconnaître", niveau: 3, radical: "reconnaiss" },
  { infinitif: "reconstruire", niveau: 3, radical: "reconstruis" },
  { infinitif: "recuire", niveau: 3, radical: "recuis" },
  { infinitif: "redire", niveau: 3, radical: "redis" },
  { infinitif: "relire", niveau: 3, radical: "relis" },
  { infinitif: "reluire", niveau: 3, radical: "reluis" },
  { infinitif: "renduire", niveau: 3, radical: "renduis" },
  { infinitif: "repartir", niveau: 3, radical: "repart" },
  { infinitif: "reproduire", niveau: 3, radical: "reproduis" },
  { infinitif: "ressentir", niveau: 2, radical: "ressent" },
  { infinitif: "resservir", niveau: 2, radical: "resserv" },
  { infinitif: "ressortir", niveau: 2, radical: "ressort" },
  { infinitif: "retranscrire", niveau: 4, radical: "retranscriv" },
  { infinitif: "revivre", niveau: 2, radical: "reviv" },
  { infinitif: "réapparaître", niveau: 4, radical: "réapparaiss" },
  { infinitif: "récrire", niveau: 3, radical: "récriv" },
  { infinitif: "réduire", niveau: 3, radical: "réduis" },
  { infinitif: "réinscrire", niveau: 4, radical: "réinscriv" },
  { infinitif: "réintroduire", niveau: 4, radical: "réintroduis" },
  { infinitif: "réécrire", niveau: 3, radical: "réécriv" },
  { infinitif: "réélire", niveau: 4, radical: "réélis" },
  { infinitif: "savoir", niveau: 2, radical: "sach" },
  { infinitif: "se rendormir", niveau: 4, radical: "rendorm", pronominal: true },
  { infinitif: "se repentir", niveau: 4, radical: "repent", pronominal: true },
  { infinitif: "se taire", niveau: 2, radical: "tais", pronominal: true },
  { infinitif: "sentir", niveau: 1, radical: "sent" },
  { infinitif: "servir", niveau: 1, radical: "serv" },
  { infinitif: "sortir", niveau: 1, radical: "sort" },
  { infinitif: "souscrire", niveau: 3, radical: "souscriv" },
  { infinitif: "suffire", niveau: 3, radical: "suffis" },
  { infinitif: "suivre", niveau: 1, radical: "suiv" },
  { infinitif: "survivre", niveau: 3, radical: "surviv" },
  { infinitif: "séduire", niveau: 2, radical: "séduis" },
  { infinitif: "s'endormir", niveau: 2, radical: "endorm", pronominal: true },
  { infinitif: "traduire", niveau: 3, radical: "traduis" },
  { infinitif: "transcrire", niveau: 4, radical: "transcriv" },
  { infinitif: "transparaître", niveau: 4, radical: "transparaiss" },
  { infinitif: "vivre", niveau: 1, radical: "viv" },
  { infinitif: "pouvoir", niveau: 4, radical: "puiss" },
  { infinitif: "vouloir", niveau: 3, radical: "veuill", radNousVous: "voul" },
  { infinitif: "valoir", niveau: 4, radical: "vaill", radNousVous: "val" },
  { infinitif: "vaincre", niveau: 4, radical: "vainqu" },
{ infinitif: "s'asseoir", niveau: 1, radical: "assoi", radAlt: "assey", radNousVous: "assoy", radNousVousAlt: "assey", pronominal: true },
{ infinitif: "apercevoir", niveau: 2, radical: "aperçoiv", radNousVous: "apercev" },
  { infinitif: "aller", niveau: 1, radical: "aill", radNousVous: "all" },
  { infinitif: "boire", niveau: 1, radical: "boiv", radNousVous: "buv" },
  { infinitif: "écrire", niveau: 1, radical: "écriv" },
  { infinitif: "émouvoir", niveau: 4, radical: "émeuv", radNousVous: "émouv" },
{ infinitif: "falloir", niveau: 1, radical: "faill", sujetsPossibles: ["il"] },
  { infinitif: "haïr", niveau: 2, radical: "haïss" },
  { infinitif: "lire", niveau: 1, radical: "lis" },
{ infinitif: "absoudre", niveau: 3, radical: "absolv" },
  { infinitif: "dissoudre", niveau: 3, radical: "dissolv" },
  { infinitif: "résoudre", niveau: 3, radical: "résolv" },
 { infinitif: "pleuvoir", niveau: 1, radical: "pleuv", sujetsPossibles: ["il"] },
{ infinitif: "être", niveau: 1, radical: "soi", radNousVous: "soy",
  // Pelotes NOUS : -ons / -ions / -ont  → bonne : -ons
  // Pelotes VOUS : -ez / -iez / -ait   → bonne : -ez
},
{ infinitif: "avoir", niveau: 1, radical: "ai", radNousVous: "ay",
  // Pelotes NOUS : -ons / -ions / -ont  → bonne : -ons
  // Pelotes VOUS : -ez / -iez / -ait   → bonne : -ez
},
 
];
