// ============================================================
// verbesImparfaitPron.js — Verbes pronominaux imparfait
// ============================================================

// Pronominaux réguliers (imparfait1)
const verbesImparfaitPron1 = [
{
  infinitif: "se dévouer",
  groupe: 1,
  niveau: 3,
  pronominal: true,
  radicalJe: "me dévou-",
  radicalTu: "te dévou-",
  radicalIl: "se dévou-",
  radicalPluriel: "se dévou-",
  radicalNous: "nous dévou-",
  radicalVous: "vous dévou-",
},
{
  infinitif: "se repentir",
  groupe: 3,
  niveau: 4,
  pronominal: true,
  radicalJe: "me repent-",
  radicalTu: "te repent-",
  radicalIl: "se repent-",
  radicalPluriel: "se repent-",
  radicalNous: "nous repent-",
  radicalVous: "vous repent-",
},
{
  infinitif: "se souvenir",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "me souven-",
  radicalTu: "te souven-",
  radicalIl: "se souven-",
  radicalPluriel: "se souven-",
  radicalNous: "nous souven-",
  radicalVous: "vous souven-",
},
{
  infinitif: "s'abstenir",
  groupe: 3,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'absten-",
  radicalTu: "t'absten-",
  radicalIl: "s'absten-",
  radicalPluriel: "s'absten-",
  radicalNous: "nous absten-",
  radicalVous: "vous absten-",
},
{
  infinitif: "s'endormir",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "m'endorm-",
  radicalTu: "t'endorm-",
  radicalIl: "s'endorm-",
  radicalPluriel: "s'endorm-",
  radicalNous: "nous endorm-",
  radicalVous: "vous endorm-",
},
{
  infinitif: "s'enquérir",
  groupe: 3,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'enquér-",
  radicalTu: "t'enquér-",
  radicalIl: "s'enquér-",
  radicalPluriel: "s'enquér-",
  radicalNous: "nous enquér-",
  radicalVous: "vous enquér-",
},
{
  infinitif: "se rendormir",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "me rendorm-",
  radicalTu: "te rendorm-",
  radicalIl: "se rendorm-",
  radicalPluriel: "se rendorm-",
  radicalNous: "nous rendorm-",
  radicalVous: "vous rendorm-",
},
{
  infinitif: "s'approprier",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'appropri-",
  radicalTu: "t'appropri-",
  radicalIl: "s'appropri-",
  radicalPluriel: "s'appropri-",
  radicalNous: "nous appropri-",
  radicalVous: "vous appropri-",
},
{
  infinitif: "s'extasier",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'extasi-",
  radicalTu: "t'extasi-",
  radicalIl: "s'extasi-",
  radicalPluriel: "s'extasi-",
  radicalNous: "nous extasi-",
  radicalVous: "vous extasi-",
},
{
  infinitif: "s'écrier",
  groupe: 1,
  niveau: 2,
  pronominal: true,
  radicalJe: "m'écri-",
  radicalTu: "t'écri-",
  radicalIl: "s'écri-",
  radicalPluriel: "s'écri-",
  radicalNous: "nous écri-",
  radicalVous: "vous écri-",
},
];

// Pronominaux altérés (imparfait2)
const verbesImparfaitPron2 = [
{
  infinitif: "se méprendre",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "me mépren-",
  radicalTu: "te mépren-",
  radicalIl: "se mépren-",
  radicalPluriel: "se mépren-",
  radicalNous: "nous mépren-",
  radicalVous: "vous mépren-",
},
{
  infinitif: "se morfondre",
  groupe: 3,
  niveau: 4,
  pronominal: true,
  radicalJe: "me morfond-",
  radicalTu: "te morfond-",
  radicalIl: "se morfond-",
  radicalPluriel: "se morfond-",
  radicalNous: "nous morfond-",
  radicalVous: "vous morfond-",
},
{
  infinitif: "se rendre",
  groupe: 3,
  niveau: 1,
  pronominal: true,
  radicalJe: "me rend-",
  radicalTu: "te rend-",
  radicalIl: "se rend-",
  radicalPluriel: "se rend-",
  radicalNous: "nous rend-",
  radicalVous: "vous rend-",
},
{
  infinitif: "s'ensuivre",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  sujetsPossibles: ["il"],
  radicalIl: "s'ensuiv-",
},
{
  infinitif: "s'éprendre",
  groupe: 3,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'épren-",
  radicalTu: "t'épren-",
  radicalIl: "s'épren-",
  radicalPluriel: "s'épren-",
  radicalNous: "nous épren-",
  radicalVous: "vous épren-",
},
{
  infinitif: "se bonifier",
  groupe: 1,
  niveau: 3,
  pronominal: true,
  radicalJe: "me bonifi-",
  radicalTu: "te bonifi-",
  radicalIl: "se bonifi-",
  radicalPluriel: "se bonifi-",
  radicalNous: "nous bonifi-",
  radicalVous: "vous bonifi-",
},
{
  infinitif: "se frayer",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "me fray-",
  radicalTu: "te fray-",
  radicalIl: "se fray-",
  radicalPluriel: "se fray-",
  radicalNous: "nous fray-",
  radicalVous: "vous fray-",
},
{
  infinitif: "se méfier",
  groupe: 1,
  niveau: 2,
  pronominal: true,
  radicalJe: "me méfi-",
  radicalTu: "te méfi-",
  radicalIl: "se méfi-",
  radicalPluriel: "se méfi-",
  radicalNous: "nous méfi-",
  radicalVous: "vous méfi-",
},
{
  infinitif: "se réfugier",
  groupe: 1,
  niveau: 3,
  pronominal: true,
  radicalJe: "me réfugi-",
  radicalTu: "te réfugi-",
  radicalIl: "se réfugi-",
  radicalPluriel: "se réfugi-",
  radicalNous: "nous réfugi-",
  radicalVous: "vous réfugi-",
},
{
  infinitif: "se soucier",
  groupe: 1,
  niveau: 3,
  pronominal: true,
  radicalJe: "me souci-",
  radicalTu: "te souci-",
  radicalIl: "se souci-",
  radicalPluriel: "se souci-",
  radicalNous: "nous souci-",
  radicalVous: "vous souci-",
},
{
  infinitif: "s'apitoyer",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'apitoi-",
  radicalTu: "t'apitoi-",
  radicalIl: "s'apitoi-",
  radicalPluriel: "s'apitoi-",
  radicalNous: "nous apitoi-",
  radicalVous: "vous apitoi-",
},
{
  infinitif: "s'approprier",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'appropri-",
  radicalTu: "t'appropri-",
  radicalIl: "s'appropri-",
  radicalPluriel: "s'appropri-",
  radicalNous: "nous appropri-",
  radicalVous: "vous appropri-",
},
{
  infinitif: "s'extasier",
  groupe: 1,
  niveau: 4,
  pronominal: true,
  radicalJe: "m'extasi-",
  radicalTu: "t'extasi-",
  radicalIl: "s'extasi-",
  radicalPluriel: "s'extasi-",
  radicalNous: "nous extasi-",
  radicalVous: "vous extasi-",
},
{
  infinitif: "s'écrier",
  groupe: 1,
  niveau: 2,
  pronominal: true,
  radicalJe: "m'écri-",
  radicalTu: "t'écri-",
  radicalIl: "s'écri-",
  radicalPluriel: "s'écri-",
  radicalNous: "nous écri-",
  radicalVous: "vous écri-",
},
{
  infinitif: "se blottir",
  groupe: 2,
  niveau: 1,
  pronominal: true,
  radicalJe: "me blottiss-",
  radicalTu: "te blottiss-",
  radicalIl: "se blottiss-",
  radicalPluriel: "se blottiss-",
  radicalNous: "nous blottiss-",
  radicalVous: "vous blottiss-",
},
{
  infinitif: "s'enhardir",
  groupe: 2,
  niveau: 1,
  pronominal: true,
  radicalJe: "m'enhardiss-",
  radicalTu: "t'enhardiss-",
  radicalIl: "s'enhardiss-",
  radicalPluriel: "s'enhardiss-",
  radicalNous: "nous enhardiss-",
  radicalVous: "vous enhardiss-",
},
{
  infinitif: "se taire",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "me tais-",
  radicalTu: "te tais-",
  radicalIl: "se tais-",
  radicalPluriel: "se tais-",
  radicalNous: "nous tais-",
  radicalVous: "vous tais-",
},
{
  infinitif: "se dédire",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "me dédis-",
  radicalTu: "te dédis-",
  radicalIl: "se dédis-",
  radicalPluriel: "se dédis-",
  radicalNous: "nous dédis-",
  radicalVous: "vous dédis-",
},
{
  infinitif: "s'enfuir",
  groupe: 3,
  niveau: 3,
  pronominal: true,
  radicalJe: "m'enfuy-",
  radicalTu: "t'enfuy-",
  radicalIl: "s'enfuy-",
  radicalPluriel: "s'enfuy-",
  radicalNous: "nous enfuy-",
  radicalVous: "vous enfuy-",
},
];
