const verbesImparfait1 = [
  {
    infinitif: "accentuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "accentu-",
  },
  {
    infinitif: "attribuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "attribu-",
  },
  {
    infinitif: "atténuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "atténu-",
  },
  {
    infinitif: "avouer",
    groupe: 1,
    niveau: 1,
    radicalImp: "avou-",
  },
  {
    infinitif: "desserrer",
    groupe: 1,
    niveau: 2,
    radicalImp: "desserr-",
  },
  {
    infinitif: "diluer",
    groupe: 1,
    niveau: 1,
    radicalImp: "dilu-",
  },
  {
    infinitif: "distribuer",
    groupe: 1,
    niveau: 3,
    radicalImp: "distribu-",
  },
  {
    infinitif: "dénouer",
    groupe: 1,
    niveau: 3,
    radicalImp: "dénou-",
  },
  {
    infinitif: "effectuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "effectu-",
  },
  {
    infinitif: "éberluer",
    groupe: 1,
    niveau: 4,
    radicalImp: "éberlu-",
  },
  {
    infinitif: "éternuer",
    groupe: 1,
    niveau: 1,
    radicalImp: "éternu-",
  },
  {
    infinitif: "évacuer",
    groupe: 1,
    niveau: 3,
    radicalImp: "évacu-",
  },
  {
    infinitif: "évaluer",
    groupe: 1,
    niveau: 3,
    radicalImp: "évalu-",
  },
  {
    infinitif: "évoluer",
    groupe: 1,
    niveau: 3,
    radicalImp: "évolu-",
  },
  {
    infinitif: "habituer",
    groupe: 1,
    niveau: 1,
    radicalImp: "habitu-",
  },
  {
    infinitif: "influer",
    groupe: 1,
    niveau: 4,
    radicalImp: "influ-",
  },
  {
    infinitif: "insinuer",
    groupe: 1,
    niveau: 3,
    radicalImp: "insinu-",
  },
  {
    infinitif: "louer",
    groupe: 1,
    niveau: 1,
    radicalImp: "lou-",
  },
  {
    infinitif: "muer",
    groupe: 1,
    niveau: 4,
    radicalImp: "mu-",
  },
  {
    infinitif: "nouer",
    groupe: 1,
    niveau: 2,
    radicalImp: "nou-",
  },
  {
    infinitif: "polluer",
    groupe: 1,
    niveau: 2,
    radicalImp: "pollu-",
  },
  {
    infinitif: "remuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "remu-",
  },
  {
    infinitif: "restituer",
    groupe: 1,
    niveau: 4,
    radicalImp: "restitu-",
  },
  {
    infinitif: "ruer",
    groupe: 1,
    niveau: 1,
    radicalImp: "ru-",
  },
  {
    infinitif: "saluer",
    groupe: 1,
    niveau: 1,
    radicalImp: "salu-",
  },
  {
    infinitif: "secouer",
    groupe: 1,
    niveau: 1,
    radicalImp: "secou-",
  },
  {
    infinitif: "situer",
    groupe: 1,
    niveau: 1,
    radicalImp: "situ-",
  },
  {
    infinitif: "statuer",
    groupe: 1,
    niveau: 4,
    radicalImp: "statu-",
  },
  {
    infinitif: "substituer",
    groupe: 1,
    niveau: 4,
    radicalImp: "substitu-",
  },
  {
    infinitif: "suer",
    groupe: 1,
    niveau: 3,
    radicalImp: "su-",
  },
  {
    infinitif: "tatouer",
    groupe: 1,
    niveau: 3,
    radicalImp: "tatou-",
  },
  {
    infinitif: "vouer",
    groupe: 1,
    niveau: 3,
    radicalImp: "vou-",
  },
  {
    infinitif: "abattre",
    groupe: 3,
    niveau: 2,
    radicalImp: "abattr-",
  },
  {
    infinitif: "accourir",
    groupe: 3,
    niveau: 3,
    radicalImp: "accour-",
  },
  {
    infinitif: "acquérir",
    groupe: 3,
    niveau: 4,
    radicalImp: "acquér-",
  },
  {
    infinitif: "apercevoir",
    groupe: 3,
    niveau: 3,
    radicalImp: "apercev-",
  },
  {
    infinitif: "apprendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "appren-",
  },
  {
    infinitif: "attendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "attend-",
  },
  {
    infinitif: "avoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "av-",
  },
  {
    infinitif: "battre",
    groupe: 3,
    niveau: 2,
    radicalImp: "batt-",
  },
  {
    infinitif: "bouillir",
    groupe: 3,
    niveau: 2,
    radicalImp: "bouill-",
  },
  {
    infinitif: "circonvenir",
    groupe: 3,
    niveau: 4,
    radicalImp: "circonven-",
  },
  {
    infinitif: "combattre",
    groupe: 3,
    niveau: 3,
    radicalImp: "combatt-",
  },
  {
    infinitif: "comprendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "compren-",
  },
  {
    infinitif: "conclure",
    groupe: 3,
    niveau: 3,
    radicalImp: "conclu-",
  },
  {
    infinitif: "concourir",
    groupe: 3,
    niveau: 3,
    radicalImp: "concour-",
  },
  {
    infinitif: "condescendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "condescend-",
},
  {
    infinitif: "confondre",
    groupe: 3,
    niveau: 2,
    radicalImp: "confond-",
  },
  {
    infinitif: "conquérir",
    groupe: 3,
    niveau: 4,
    radicalImp: "conquér-",
  },
  {
    infinitif: "consentir",
    groupe: 3,
    niveau: 2,
    radicalImp: "consent-",
  },
  {
    infinitif: "contenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "conten-",
  },
  {
    infinitif: "contrevenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "contreven-",
  },
  {
    infinitif: "convenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "conven-",
  },
  {
    infinitif: "correspondre",
    groupe: 3,
    niveau: 3,
    radicalImp: "correspond-",
  },
  {
    infinitif: "courir",
    groupe: 3,
    niveau: 1,
    radicalImp: "cour-",
  },
  {
    infinitif: "descendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "descend-",
  },
  {
    infinitif: "devenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "deven-",
  },
  {
    infinitif: "devoir",
    groupe: 3,
    niveau: 1,
    radicalImp: "dev-",
  },
  {
    infinitif: "disconvenir",
    groupe: 3,
    niveau: 4,
    radicalImp: "disconven-",
  },
  {
    infinitif: "discourir",
    groupe: 3,
    niveau: 4,
    radicalImp: "discour-",
  },
  {
    infinitif: "distendre",
    groupe: 3,
    niveau: 4,
    radicalImp: "distend-",
  },
  {
    infinitif: "dormir",
    groupe: 3,
    niveau: 1,
    radicalImp: "dorm-",
},
  {
    infinitif: "démentir",
    groupe: 3,
    niveau: 3,
    radicalImp: "dément-",
  },
  {
    infinitif: "démordre",
    groupe: 3,
    niveau: 3,
    radicalImp: "démord-",
  },
  {
    infinitif: "départir",
    groupe: 3,
    niveau: 4,
    radicalImp: "départ-",
  },
  {
    infinitif: "dépendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "dépend-",
  },
  {
    infinitif: "détendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "détend-",
  },
  {
    infinitif: "détenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "déten-",
  },
  {
    infinitif: "encourir",
    groupe: 3,
    niveau: 4,
    radicalImp: "encour-",
  },
  {
    infinitif: "entendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "entend-",
  },
  {
    infinitif: "entreprendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "entrepren-",
  },
  {
    infinitif: "entretenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "entreten-",
  },
  {
    infinitif: "émouvoir",
    groupe: 3,
    niveau: 4,
    radicalImp: "émouv-",
  },
  {
    infinitif: "falloir",
    groupe: 3,
    niveau: 2,
    radicalImp: "fall-",
    sujetsPossibles: ["il"],
  },
  {
    infinitif: "fendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "fend-",
  },
  {
    infinitif: "fondre",
    groupe: 3,
    niveau: 3,
    radicalImp: "fond-",
  },
  {
    infinitif: "intervenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "interven-",
  },
  {
    infinitif: "maintenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "mainten-",
  },
  {
    infinitif: "mentir",
    groupe: 3,
    niveau: 3,
    radicalImp: "ment-",
  },
  {
    infinitif: "mordre",
    groupe: 3,
    niveau: 2,
    radicalImp: "mord-",
  },
  {
    infinitif: "obtenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "obten-",
  },
  {
    infinitif: "parcourir",
    groupe: 3,
    niveau: 3,
    radicalImp: "parcour-",
  },
  {
    infinitif: "partir",
    groupe: 3,
    niveau: 1,
    radicalImp: "part-",
  },
  {
    infinitif: "parvenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "parven-",
  },
  {
    infinitif: "pendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "pend-",
  },
  {
    infinitif: "perdre",
    groupe: 3,
    niveau: 3,
    radicalImp: "perd-",
  },
  {
    infinitif: "pleuvoir",
    groupe: 3,
    niveau: 1,
    radicalImp: "pleuv-",
    sujetsPossibles: ["il"],
  },
  {
    infinitif: "pondre",
    groupe: 3,
    niveau: 3,
    radicalImp: "pond-",
  },
  {
    infinitif: "pourfendre",
    groupe: 3,
    niveau: 4,
    radicalImp: "pourfend-",
  },
  {
    infinitif: "pouvoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "pouv-",
  },
  {
    infinitif: "prendre",
    groupe: 3,
    niveau: 1,
    radicalImp: "pren-",
  },
  {
    infinitif: "prescrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "prescriv-",
  },
  {
    infinitif: "pressentir",
    groupe: 3,
    niveau: 3,
    radicalImp: "pressent-",
  },
  {
    infinitif: "promouvoir",
    groupe: 3,
    niveau: 4,
    radicalImp: "promouv-",
  },
  {
    infinitif: "provenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "proven-",
  },
  {
    infinitif: "prétendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "prétend-",
  },
  {
    infinitif: "prévaloir",
    groupe: 3,
    niveau: 3,
    radicalImp: "préval-",
  },
  {
    infinitif: "prévenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "préven-",
  },
  {
    infinitif: "recourir",
    groupe: 3,
    niveau: 3,
    radicalImp: "recour-",
  },
  {
    infinitif: "redevenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "redeven-",
  },
  {
    infinitif: "rendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "rend-",
  },
  {
    infinitif: "repartir",
    groupe: 3,
    niveau: 2,
    radicalImp: "repart-",
  },
  {
    infinitif: "requérir",
    groupe: 3,
    niveau: 4,
    radicalImp: "requér-",
  },
  {
    infinitif: "ressentir",
    groupe: 3,
    niveau: 3,
    radicalImp: "ressent-",
  },
  {
    infinitif: "resservir",
    groupe: 3,
    niveau: 3,
    radicalImp: "resserv-",
  },
  {
    infinitif: "ressortir",
    groupe: 3,
    niveau: 2,
    radicalImp: "ressort-",
    sujetsPossibles: ["je", "tu", "il"],
  },
  {
    infinitif: "retenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "reten-",
  },
  {
    infinitif: "revendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "revend-",
  },
  {
    infinitif: "revenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "reven-",
  },
  {
    infinitif: "revivre",
    groupe: 3,
    niveau: 3,
    radicalImp: "reviv-",
  },
  {
    infinitif: "rire",
    groupe: 3,
    niveau: 1,
    radicalImp: "ri-",
  }, 
  {
    infinitif: "répandre",
    groupe: 3,
    niveau: 3,
    radicalImp: "répand-",
  },
  {
    infinitif: "répartir",
    groupe: 3,
    niveau: 3,
    radicalImp: "répart-",
  },
  {
    infinitif: "répondre",
    groupe: 3,
    niveau: 1,
    radicalImp: "répond-",
  },
  {
    infinitif: "savoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "sav-",
  },
  {
    infinitif: "secourir",
    groupe: 3,
    niveau: 2,
    radicalImp: "secour-",
  },
  {
    infinitif: "sentir",
    groupe: 3,
    niveau: 1,
    radicalImp: "sent-",
  },
  {
    infinitif: "servir",
    groupe: 3,
    niveau: 1,
    radicalImp: "serv-",
  },
  {
    infinitif: "sortir",
    groupe: 3,
    niveau: 1,
    radicalImp: "sort-",
  },
  {
    infinitif: "soutenir",
    groupe: 3,
    niveau: 2,
    radicalImp: "souten-",
  },
  {
    infinitif: "subvenir",
    groupe: 3,
    niveau: 4,
    radicalImp: "subven-",
  },
  {
    infinitif: "suivre",
    groupe: 3,
    niveau: 2,
    radicalImp: "suiv-",
  },
  {
    infinitif: "surprendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "surpren-",
  },
  {
    infinitif: "survenir",
    groupe: 3,
    niveau: 3,
    radicalImp: "surven-",
  },
  {
    infinitif: "survivre",
    groupe: 3,
    niveau: 3,
    radicalImp: "surviv-",
  },
  {
    infinitif: "suspendre",
    groupe: 3,
    niveau: 3,
    radicalImp: "suspend-",
  },
  {
    infinitif: "tendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "tend-",
  },
  {
    infinitif: "tenir",
    groupe: 3,
    niveau: 1,
    radicalImp: "ten-",
  },
  {
    infinitif: "tordre",
    groupe: 3,
    niveau: 3,
    radicalImp: "tord-",
  },
  {
    infinitif: "valoir",
    groupe: 3,
    niveau: 3,
    radicalImp: "val-",
  },
  {
    infinitif: "vendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "vend-",
  },
  {
    infinitif: "venir",
    groupe: 3,
    niveau: 1,
    radicalImp: "ven-",
  },
  {
    infinitif: "vivre",
    groupe: 3,
    niveau: 2,
    radicalImp: "viv-",
  },
  {
    infinitif: "vouloir",
    groupe: 3,
    niveau: 2,
    radicalImp: "voul-",
  },
  // --- Verbes en -GUER (u toujours présent, réguliers) ---
  { infinitif: "conjuguer",  groupe: 1, niveau: 1, radicalImp: "conjugu-" },
  { infinitif: "fatiguer",   groupe: 1, niveau: 1, radicalImp: "fatigu-" },
  { infinitif: "naviguer",   groupe: 1, niveau: 2, radicalImp: "navigu-" },
  { infinitif: "distinguer", groupe: 1, niveau: 3, radicalImp: "distingu-" },
  { infinitif: "narguer",    groupe: 1, niveau: 4, radicalImp: "nargu-" },
  { infinitif: "divulguer",  groupe: 1, niveau: 4, radicalImp: "divulgu-" },
{
  infinitif: "aller",
  groupe: 3,
  niveau: 1,
  radicalImp: "all-",
},
];

const verbesImparfait2 = [
  {
    infinitif: "aboyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "aboy-",
  },
  {
    infinitif: "amplifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "amplifi-",
  },
  {
    infinitif: "apparier",
    groupe: 1,
    niveau: 4,
    radicalImp: "appari-",
  },
  {
    infinitif: "apprécier",
    groupe: 1,
    niveau: 3,
    radicalImp: "appréci-",
  },
  {
    infinitif: "appuyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "appuy-",
  },
  {
    infinitif: "associer",
    groupe: 1,
    niveau: 2,
    radicalImp: "associ-",
  },
  {
    infinitif: "balayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "balay-",
  },
  {
    infinitif: "balbutier",
    groupe: 1,
    niveau: 2,
    radicalImp: "balbuti-",
  },
  {
    infinitif: "bayer",
    groupe: 1,
    niveau: 3,
    radicalImp: "bay-",
  },
  {
    infinitif: "broyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "broy-",
  },
  {
    infinitif: "bégayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "bégay-",
  },
  {
    infinitif: "bénéficier",
    groupe: 1,
    niveau: 3,
    radicalImp: "bénéfici-",
  },
  {
    infinitif: "certifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "certifi-",
  },
  {
    infinitif: "charrier",
    groupe: 1,
    niveau: 3,
    radicalImp: "charri-",
  },
  {
    infinitif: "chatoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "chatoy-",
  },
  {
    infinitif: "choyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "choy-",
  },
  {
    infinitif: "châtier",
    groupe: 1,
    niveau: 4,
    radicalImp: "châti-",
  },
  {
    infinitif: "clarifier",
    groupe: 1,
    niveau: 2,
    radicalImp: "clarifi-",
  },
  {
    infinitif: "colorier",
    groupe: 1,
    niveau: 2,
    radicalImp: "colori-",
  },
  {
    infinitif: "complexifier",
    groupe: 1,
    niveau: 4,
    radicalImp: "complexifi-",
  },
  {
    infinitif: "concilier",
    groupe: 1,
    niveau: 3,
    radicalImp: "concili-",
  },
  {
    infinitif: "contrarier",
    groupe: 1,
    niveau: 3,
    radicalImp: "contrari-",
  },
  {
    infinitif: "convier",
    groupe: 1,
    niveau: 3,
    radicalImp: "convi-",
  },
  {
    infinitif: "convoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "convoy-",
  },
  {
    infinitif: "crier",
    groupe: 1,
    niveau: 1,
    radicalImp: "cri-",
  },
  {
    infinitif: "différencier",
    groupe: 1,
    niveau: 4,
    radicalImp: "différenci-",
  },
  {
    infinitif: "déblayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "déblay-",
  },
  {
    infinitif: "décrier",
    groupe: 1,
    niveau: 3,
    radicalImp: "décri-",
  },
  {
    infinitif: "dédier",
    groupe: 1,
    niveau: 3,
    radicalImp: "dédi-",
  },
  {
    infinitif: "défier",
    groupe: 1,
    niveau: 2,
    radicalImp: "défi-",
  },
  {
    infinitif: "défrayer",
    groupe: 1,
    niveau: 4,
    radicalImp: "défray-",
  },
  {
    infinitif: "délayer",
    groupe: 1,
    niveau: 3,
    radicalImp: "délay-",
  },
  {
    infinitif: "délier",
    groupe: 1,
    niveau: 2,
    radicalImp: "déli-",
  },
  {
    infinitif: "dénier",
    groupe: 1,
    niveau: 4,
    radicalImp: "déni-",
  },
  {
    infinitif: "déplier",
    groupe: 1,
    niveau: 1,
    radicalImp: "dépli-",
  },
  {
    infinitif: "déployer",
    groupe: 1,
    niveau: 3,
    radicalImp: "déploy-",
  },
  {
    infinitif: "dévoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "dévoy-",
  },
  {
    infinitif: "effrayer",
    groupe: 1,
    niveau: 1,
    radicalImp: "effray-",
  },
  {
    infinitif: "employer",
    groupe: 1,
    niveau: 2,
    radicalImp: "employ-",
  },
  {
    infinitif: "ennuyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "ennuy-",
  },
  {
    infinitif: "enrayer",
    groupe: 1,
    niveau: 3,
    radicalImp: "enray-",
  },
  {
    infinitif: "envier",
    groupe: 1,
    niveau: 1,
    radicalImp: "envi-",
  },
  {
    infinitif: "envoyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "envoy-",
  },
  {
    infinitif: "essayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "essay-",
  },
  {
    infinitif: "essuyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "essuy-",
  },
  {
    infinitif: "expédier",
    groupe: 1,
    niveau: 3,
    radicalImp: "expédi-",
  },
  {
    infinitif: "égayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "égay-",
  },
  {
    infinitif: "épier",
    groupe: 1,
    niveau: 1,
    radicalImp: "épi-",
  },
  {
    infinitif: "étayer",
    groupe: 1,
    niveau: 3,
    radicalImp: "étay-",
  },
  {
    infinitif: "étudier",
    groupe: 1,
    niveau: 1,
    radicalImp: "étudi-",
  },
  {
    infinitif: "festoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "festoy-",
  },
  {
    infinitif: "flamboyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "flamboy-",
  },
  {
    infinitif: "foudroyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "foudroy-",
  },
  {
    infinitif: "fourvoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "fourvoy-",
  },
  {
    infinitif: "humilier",
    groupe: 1,
    niveau: 3,
    radicalImp: "humili-",
  },
  {
    infinitif: "identifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "identifi-",
  },
  {
    infinitif: "initier",
    groupe: 1,
    niveau: 3,
    radicalImp: "initi-",
  },
  {
    infinitif: "intensifier",
    groupe: 1,
    niveau: 4,
    radicalImp: "intensifi-",
  },
  {
    infinitif: "justifier",
    groupe: 1,
    niveau: 2,
    radicalImp: "justifi-",
  },
  {
    infinitif: "larmoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "larmoy-",
  },
  {
    infinitif: "licencier",
    groupe: 1,
    niveau: 3,
    radicalImp: "licenci-",
  },
  {
    infinitif: "lier",
    groupe: 1,
    niveau: 1,
    radicalImp: "li-",
  },
  {
    infinitif: "louvoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "louvoy-",
  },
  {
    infinitif: "manier",
    groupe: 1,
    niveau: 3,
    radicalImp: "mani-",
  },
  {
    infinitif: "marier",
    groupe: 1,
    niveau: 1,
    radicalImp: "mari-",
  },
  {
    infinitif: "maugréer",
    groupe: 1,
    niveau: 4,
    radicalImp: "maugré-",
  },
  {
    infinitif: "mendier",
    groupe: 1,
    niveau: 2,
    radicalImp: "mendi-",
  },
  {
    infinitif: "modifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "modifi-",
  },
  {
    infinitif: "monnayer",
    groupe: 1,
    niveau: 4,
    radicalImp: "monnay-",
  },
  {
    infinitif: "multiplier",
    groupe: 1,
    niveau: 3,
    radicalImp: "multipli-",
  },
  {
    infinitif: "nettoyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "nettoy-",
  },
  {
    infinitif: "nier",
    groupe: 1,
    niveau: 3,
    radicalImp: "ni-",
  },
  {
    infinitif: "notifier",
    groupe: 1,
    niveau: 2,
    radicalImp: "notifi-",
  },
  {
    infinitif: "noyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "noy-",
  },
  {
    infinitif: "négocier",
    groupe: 1,
    niveau: 3,
    radicalImp: "négoci-",
  },
  {
    infinitif: "octroyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "octroy-",
  },
  {
    infinitif: "officier",
    groupe: 1,
    niveau: 4,
    radicalImp: "offici-",
  },
  {
    infinitif: "oublier",
    groupe: 1,
    niveau: 1,
    radicalImp: "oubli-",
  },
  {
    infinitif: "pagayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "pagay-",
  },
  {
    infinitif: "pallier",
    groupe: 1,
    niveau: 3,
    radicalImp: "palli-",
  },
  {
    infinitif: "parier",
    groupe: 1,
    niveau: 1,
    radicalImp: "pari-",
  },
  {
    infinitif: "payer",
    groupe: 1,
    niveau: 1,
    radicalImp: "pay-",
  },
  {
    infinitif: "photographier",
    groupe: 1,
    niveau: 3,
    radicalImp: "photographi-",
  },
  {
    infinitif: "planifier",
    groupe: 1,
    niveau: 2,
    radicalImp: "planifi-",
  },
  {
    infinitif: "plier",
    groupe: 1,
    niveau: 1,
    radicalImp: "pli-",
  },
  {
    infinitif: "ployer",
    groupe: 1,
    niveau: 3,
    radicalImp: "ploy-",
  },
  {
    infinitif: "privilégier",
    groupe: 1,
    niveau: 4,
    radicalImp: "privilégi-",
  },
  {
    infinitif: "publier",
    groupe: 1,
    niveau: 2,
    radicalImp: "publi-",
  },
  {
    infinitif: "qualifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "qualifi-",
  },
  {
    infinitif: "rallier",
    groupe: 1,
    niveau: 3,
    radicalImp: "ralli-",
  },
  {
    infinitif: "rapatrier",
    groupe: 1,
    niveau: 3,
    radicalImp: "rapatri-",
  },
  {
    infinitif: "rassasier",
    groupe: 1,
    niveau: 4,
    radicalImp: "rassasi-",
  },
  {
    infinitif: "rayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "ray-",
  },
  {
    infinitif: "recopier",
    groupe: 1,
    niveau: 2,
    radicalImp: "recopi-",
  },
  {
    infinitif: "recréer",
    groupe: 1,
    niveau: 3,
    radicalImp: "recré-",
  },
  {
    infinitif: "rectifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "rectifi-",
  },
  {
    infinitif: "relayer",
    groupe: 1,
    niveau: 2,
    radicalImp: "relay-",
  },
  {
    infinitif: "relier",
    groupe: 1,
    niveau: 2,
    radicalImp: "reli-",
  },
  {
    infinitif: "remblayer",
    groupe: 1,
    niveau: 4,
    radicalImp: "remblay-",
  },
  {
    infinitif: "remercier",
    groupe: 1,
    niveau: 2,
    radicalImp: "remerci-",
  },
  {
    infinitif: "remédier",
    groupe: 1,
    niveau: 4,
    radicalImp: "remédi-",
  },
  {
    infinitif: "renier",
    groupe: 1,
    niveau: 4,
    radicalImp: "reni-",
  },
  {
    infinitif: "renvoyer",
    groupe: 1,
    niveau: 2,
    radicalImp: "renvoy-",
  },
  {
    infinitif: "replier",
    groupe: 1,
    niveau: 2,
    radicalImp: "repli-",
  },
  {
    infinitif: "réconcilier",
    groupe: 1,
    niveau: 3,
    radicalImp: "réconcili-",
  },
  {
    infinitif: "répertorier",
    groupe: 1,
    niveau: 4,
    radicalImp: "répertori-",
  },
  {
    infinitif: "résilier",
    groupe: 1,
    niveau: 3,
    radicalImp: "résili-",
  },
  {
    infinitif: "sacrifier",
    groupe: 1,
    niveau: 4,
    radicalImp: "sacrifi-",
  },
  {
    infinitif: "scier",
    groupe: 1,
    niveau: 2,
    radicalImp: "sci-",
  },
  {
    infinitif: "signifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "signifi-",
  },
  {
    infinitif: "simplifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "simplifi-",
  },
  {
    infinitif: "skier",
    groupe: 1,
    niveau: 1,
    radicalImp: "ski-",
  },
  {
    infinitif: "soudoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "soudoy-",
  },
  {
    infinitif: "spécifier",
    groupe: 1,
    niveau: 3,
    radicalImp: "spécifi-",
  },
  {
    infinitif: "stupéfier",
    groupe: 1,
    niveau: 4,
    radicalImp: "stupéfi-",
  },
  {
    infinitif: "supplier",
    groupe: 1,
    niveau: 3,
    radicalImp: "suppli-",
  },
  {
    infinitif: "suppléer",
    groupe: 1,
    niveau: 4,
    radicalImp: "supplé-",
  },
  {
    infinitif: "tournoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "tournoy-",
  },
  {
    infinitif: "trier",
    groupe: 1,
    niveau: 3,
    radicalImp: "tri-",
  },
  {
    infinitif: "tutoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "tutoy-",
  },
  {
    infinitif: "varier",
    groupe: 1,
    niveau: 2,
    radicalImp: "vari-",
  },
  {
    infinitif: "verdoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "verdoy-",
  },
  {
    infinitif: "vouvoyer",
    groupe: 1,
    niveau: 3,
    radicalImp: "vouvoy-",
  },
  {
    infinitif: "vérifier",
    groupe: 1,
    niveau: 2,
    radicalImp: "vérifi-",
  },
  {
    infinitif: "zézayer",
    groupe: 1,
    niveau: 4,
    radicalImp: "zézay-",
  },
  {
    infinitif: "agir",
    groupe: 2,
    niveau: 1,
    radicalImp: "agiss-",
  },
  {
    infinitif: "applaudir",
    groupe: 2,
    niveau: 3,
    radicalImp: "applaudiss-",
  },
  {
    infinitif: "arrondir",
    groupe: 2,
    niveau: 1,
    radicalImp: "arrondiss-",
  },
  {
    infinitif: "avertir",
    groupe: 2,
    niveau: 2,
    radicalImp: "avertiss-",
  },
  {
    infinitif: "blanchir",
    groupe: 2,
    niveau: 1,
    radicalImp: "blanchiss-",
  },
  {
    infinitif: "blondir",
    groupe: 2,
    niveau: 2,
    radicalImp: "blondiss-",
  },
  {
    infinitif: "blêmir",
    groupe: 2,
    niveau: 3,
    radicalImp: "blêmiss-",
  },
  {
    infinitif: "bondir",
    groupe: 2,
    niveau: 1,
    radicalImp: "bondiss-",
  },
  {
    infinitif: "bruire",
    groupe: 2,
    niveau: 4,
    radicalImp: "bruiss-",
sujetsPossibles: ["il", "elle", "ils", "elles"],
  },
  {
    infinitif: "brunir",
    groupe: 2,
    niveau: 2,
    radicalImp: "bruniss-",
  },
  {
    infinitif: "bâtir",
    groupe: 2,
    niveau: 2,
    radicalImp: "bâtiss-",
  },
  {
    infinitif: "bénir",
    groupe: 2,
    niveau: 2,
    radicalImp: "béniss-",
  },
  {
    infinitif: "choisir",
    groupe: 2,
    niveau: 1,
    radicalImp: "choisiss-",
  },
  {
    infinitif: "clapir",
    groupe: 2,
    niveau: 1,
    radicalImp: "clapiss-",
  },
  {
    infinitif: "divertir",
    groupe: 2,
    niveau: 2,
    radicalImp: "divertiss-",
  },
  {
    infinitif: "définir",
    groupe: 2,
    niveau: 1,
    radicalImp: "définiss-",
  },
  {
    infinitif: "embellir",
    groupe: 2,
    niveau: 1,
    radicalImp: "embelliss-",
  },
  {
    infinitif: "emplir",
    groupe: 2,
    niveau: 1,
    radicalImp: "empliss-",
  },
  {
    infinitif: "enfouir",
    groupe: 2,
    niveau: 1,
    radicalImp: "enfouiss-",
  },
  {
    infinitif: "engloutir",
    groupe: 2,
    niveau: 1,
    radicalImp: "engloutiss-",
  },
  {
    infinitif: "enrichir",
    groupe: 2,
    niveau: 3,
    radicalImp: "enrichiss-",
  },
  {
    infinitif: "envahir",
    groupe: 2,
    niveau: 3,
    radicalImp: "envahiss-",
  },
  {
    infinitif: "éblouir",
    groupe: 2,
    niveau: 1,
    radicalImp: "éblouiss-",
  },
  {
    infinitif: "éclaircir",
    groupe: 2,
    niveau: 2,
    radicalImp: "éclairciss-",
  },
  {
    infinitif: "élargir",
    groupe: 2,
    niveau: 1,
    radicalImp: "élargiss-",
  },
  {
    infinitif: "épaissir",
    groupe: 2,
    niveau: 2,
    radicalImp: "épaississ-",
  },
  {
    infinitif: "établir",
    groupe: 2,
    niveau: 2,
    radicalImp: "établiss-",
  },
  {
    infinitif: "finir",
    groupe: 2,
    niveau: 2,
    radicalImp: "finiss-",
  },
 {
  infinitif: "haïr",
  groupe: 2,
  niveau: 3,
  radicalImp: "haïss-",
  hAspire: true,
},
  {
    infinitif: "pâlir",
    groupe: 2,
    niveau: 2,
    radicalImp: "pâliss-",
  },
  {
    infinitif: "réunir",
    groupe: 2,
    niveau: 1,
    radicalImp: "réuniss-",
  },
  {
    infinitif: "réussir",
    groupe: 2,
    niveau: 3,
    radicalImp: "réussiss-",
  },
{
  infinitif: "hennir",
  groupe: 2,
  niveau: 4,
  radicalImp: "henniss-",
  hAspire: true,
  sujetsPossibles: ["il", "elle", "ils", "elles"],
},
  {
    infinitif: "apparaître",
    groupe: 3,
    niveau: 3,
    radicalImp: "apparaiss-",
  },
  {
    infinitif: "astreindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "astreign-",
  },
  {
    infinitif: "atteindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "atteign-",
  },
  {
    infinitif: "comparaître",
    groupe: 3,
    niveau: 4,
    radicalImp: "comparaiss-",
  },
  {
    infinitif: "complaire",
    groupe: 3,
    niveau: 3,
    radicalImp: "complais-",
  },
  {
    infinitif: "connaître",
    groupe: 3,
    niveau: 3,
    radicalImp: "connaiss-",
  },
  {
    infinitif: "contraindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "contraign-",
  },
  {
    infinitif: "craindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "craign-",
  },
  {
    infinitif: "croire",
    groupe: 3,
    niveau: 2,
    radicalImp: "croy-",
  },
  {
    infinitif: "disparaître",
    groupe: 3,
    niveau: 4,
    radicalImp: "disparaiss-",
  },
  {
    infinitif: "dépeindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "dépeign-",
  },
  {
    infinitif: "déplaire",
    groupe: 3,
    niveau: 3,
    radicalImp: "déplais-",
  },
  {
    infinitif: "déteindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "déteign-",
  },
  {
    infinitif: "enfreindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "enfreign-",
  },
  {
    infinitif: "enjoindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "enjoign-",
  },
  {
    infinitif: "être",
    groupe: 3,
    niveau: 2,
    radicalImp: "ét-",
  },
  {
    infinitif: "faire",
    groupe: 3,
    niveau: 2,
    radicalImp: "fais-",
  },
  {
    infinitif: "feindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "feign-",
  },
  {
    infinitif: "geindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "geign-",
  },
  {
    infinitif: "joindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "joign-",
  },
  {
    infinitif: "méconnaître",
    groupe: 3,
    niveau: 4,
    radicalImp: "méconnaiss-",
  },
  {
    infinitif: "naître",
    groupe: 3,
    niveau: 3,
    radicalImp: "naiss-",
  },
  {
    infinitif: "oindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "oign-",
  },
  {
    infinitif: "paraître",
    groupe: 3,
    niveau: 3,
    radicalImp: "paraiss-",
  },
  {
    infinitif: "peindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "peign-",
  },
  {
    infinitif: "plaindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "plaign-",
  },
  {
    infinitif: "plaire",
    groupe: 3,
    niveau: 2,
    radicalImp: "plais-",
  },
  {
    infinitif: "pourvoir",
    groupe: 3,
    niveau: 4,
    radicalImp: "pourvoy-",
  },
  {
    infinitif: "prévoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "prévoy-",
  },
  {
    infinitif: "reconnaître",
    groupe: 3,
    niveau: 3,
    radicalImp: "reconnaiss-",
  },
  {
    infinitif: "rejoindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "rejoign-",
  },
  {
    infinitif: "repeindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "repeign-",
  },
  {
    infinitif: "restreindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "restreign-",
  },
  {
    infinitif: "revoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "revoy-",
  },
  {
    infinitif: "réapparaître",
    groupe: 3,
    niveau: 4,
    radicalImp: "réapparaiss-",
  },
  {
    infinitif: "résoudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "résolv-",
  },
  {
    infinitif: "teindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "teign-",
  },
  {
    infinitif: "transparaître",
    groupe: 3,
    niveau: 4,
    radicalImp: "transparaiss-",
  },
  {
    infinitif: "voir",
    groupe: 3,
    niveau: 2,
    radicalImp: "voy-",
  },
  {
    infinitif: "cuire",
    groupe: 3,
    niveau: 3,
    radicalImp: "cuis-",
  },
 {
    infinitif: "asseoir",
    groupe: 3,
    niveau: 2,
    radicalImp: "assey-",
  },
  {
    infinitif: "dire",
    groupe: 3,
    niveau: 1,
    radicalImp: "dis-",
  },
  {
    infinitif: "découdre",
    groupe: 3,
    niveau: 4,
    radicalImp: "décous-",
  },
  {
    infinitif: "décrire",
    groupe: 3,
    niveau: 2,
    radicalImp: "décriv-",
  },
  {
    infinitif: "déduire",
    groupe: 3,
    niveau: 3,
    radicalImp: "déduis-",
  },
  {
    infinitif: "défaire",
    groupe: 3,
    niveau: 3,
    radicalImp: "défais-",
  },
{
    infinitif: "boire",
    groupe: 3,
    niveau: 3,
    radicalImp: "buv-",
  },
  {
    infinitif: "circonscrire",
    groupe: 3,
    niveau: 3,
    radicalImp: "circonscriv-",
  },
  {
    infinitif: "conduire",
    groupe: 3,
    niveau: 1,
    radicalImp: "conduis-",
  },
  {
    infinitif: "confire",
    groupe: 3,
    niveau: 2,
    radicalImp: "confis-",
  },
  {
    infinitif: "construire",
    groupe: 3,
    niveau: 2,
    radicalImp: "construis-",
  },
  {
    infinitif: "contredire",
    groupe: 3,
    niveau: 3,
    radicalImp: "contredis-",
  },
  {
    infinitif: "contrefaire",
    groupe: 3,
    niveau: 2,
    radicalImp: "contrefais-",
  },
  {
    infinitif: "coudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "cous-",
  },
 {
    infinitif: "gésir",
    groupe: 3,
    niveau: 4,
    radicalImp: "gis-",
  },
{
    infinitif: "éconduire",
    groupe: 3,
    niveau: 4,
    radicalImp: "éconduis-",
  },
 {
    infinitif: "détruire",
    groupe: 3,
    niveau: 3,
    radicalImp: "détruis-",
  },
  {
    infinitif: "enduire",
    groupe: 3,
    niveau: 4,
    radicalImp: "enduis-",
  },
  {
    infinitif: "écrire",
    groupe: 3,
    niveau: 1,
    radicalImp: "écriv-",
  },
  {
    infinitif: "élire",
    groupe: 3,
    niveau: 3,
    radicalImp: "élis-",
  },
  {
    infinitif: "fuir",
    groupe: 3,
    niveau: 1,
    radicalImp: "fuy-",
  },
  {
    infinitif: "induire",
    groupe: 3,
    niveau: 4,
    radicalImp: "induis-",
  },
  {
    infinitif: "inscrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "inscriv-",
  },
  {
    infinitif: "instruire",
    groupe: 3,
    niveau: 3,
    radicalImp: "instruis-",
  },
  {
    infinitif: "interdire",
    groupe: 3,
    niveau: 3,
    radicalImp: "interdis-",
  },
{
    infinitif: "recuire",
    groupe: 3,
    niveau: 3,
    radicalImp: "recuis-",
  },
{
    infinitif: "reconstruire",
    groupe: 3,
    niveau: 4,
    radicalImp: "recontruis-",
  },
  {
    infinitif: "recoudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "recous-",
  },
 {
    infinitif: "proscrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "proscriv-",
  },
 {
    infinitif: "produire",
    groupe: 3,
    niveau: 3,
    radicalImp: "produis-",
  },
{
    infinitif: "ouïr",
    groupe: 3,
    niveau: 4,
    radicalImp: "oy-",
  },
{
    infinitif: "nuire",
    groupe: 3,
    niveau: 3,
    radicalImp: "nuis-",
  },
 {
    infinitif: "mouvoir",
    groupe: 3,
    niveau: 4,
    radicalImp: "mouv-",
  },
 {
    infinitif: "introduire",
    groupe: 3,
    niveau: 3,
    radicalImp: "introduis-",
  },
  {
    infinitif: "lire",
    groupe: 3,
    niveau: 2,
    radicalImp: "lis-",
  },
  {
    infinitif: "luire",
    groupe: 3,
    niveau: 2,
    radicalImp: "luis-",
  },
  {
    infinitif: "moudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "moul-",
  },
  {
    infinitif: "méfaire",
    groupe: 3,
    niveau: 3,
    radicalImp: "méfais-",
  },
 {
    infinitif: "reproduire",
    groupe: 3,
    niveau: 4,
    radicalImp: "reproduis-",
  },
 {
    infinitif: "renduire",
    groupe: 3,
    niveau: 4,
    radicalImp: "renduis-",
  },
 {
    infinitif: "redire",
    groupe: 3,
    niveau: 2,
    radicalImp: "redis-",
  },
  {
    infinitif: "refaire",
    groupe: 3,
    niveau: 2,
    radicalImp: "refais-",
  },
  {
    infinitif: "relire",
    groupe: 3,
    niveau: 2,
    radicalImp: "relis-",
  },
  {
    infinitif: "reluire",
    groupe: 3,
    niveau: 3,
    radicalImp: "reluis-",
  },
  {
    infinitif: "remoudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "remoul-",
  },
 {
    infinitif: "suffire",
    groupe: 3,
    niveau: 2,
    radicalImp: "suffis-",
  },
{
    infinitif: "sourire",
    groupe: 3,
    niveau: 2,
    radicalImp: "souri-",
  },
 {
    infinitif: "réécrire",
    groupe: 3,
    niveau: 2,
    radicalImp: "réécriv-",
  },
  {
    infinitif: "réélire",
    groupe: 3,
    niveau: 4,
    radicalImp: "réélis-",
  },
{
    infinitif: "récrire",
    groupe: 3,
    niveau: 3,
    radicalImp: "récriv-",
  },
 {
    infinitif: "retranscrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "retranscriv-",
  },
  {
    infinitif: "réduire",
    groupe: 3,
    niveau: 3,
    radicalImp: "réduis-",
  },
  {
    infinitif: "réinscrire",
    groupe: 3,
    niveau: 3,
    radicalImp: "réinscriv-",
  },
  {
    infinitif: "réintroduire",
    groupe: 3,
    niveau: 4,
    radicalImp: "réintroduis-",
  },
  {
    infinitif: "satisfaire",
    groupe: 3,
    niveau: 3,
    radicalImp: "satisfais-",
  },
  {
    infinitif: "souscrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "souscriv-",
  },
 {
    infinitif: "traduire",
    groupe: 3,
    niveau: 3,
    radicalImp: "traduis-",
  },
  {
    infinitif: "transcrire",
    groupe: 3,
    niveau: 4,
    radicalImp: "transcriv-",
  },
 {
    infinitif: "surproduire",
    groupe: 3,
    niveau: 3,
    radicalImp: "surproduis-",
  },
 {
    infinitif: "séduire",
    groupe: 3,
    niveau: 2,
    radicalImp: "séduis-",
  },
  // --- Verbes en -GER (radical avec -e- sauf nous/vous) ---
  { infinitif: "manger",      groupe: 1, niveau: 1, radicalImp: "mange-",      radicalNous: "mang-", radicalVous: "mang-" },
  { infinitif: "nager",       groupe: 1, niveau: 1, radicalImp: "nage-",       radicalNous: "nag-", radicalVous: "nag-" },
  { infinitif: "ranger",      groupe: 1, niveau: 1, radicalImp: "range-",      radicalNous: "rang-", radicalVous: "rang-" },
  { infinitif: "changer",     groupe: 1, niveau: 1, radicalImp: "change-",     radicalNous: "chang-", radicalVous: "chang-" },
  { infinitif: "voyager",     groupe: 1, niveau: 2, radicalImp: "voyage-",     radicalNous: "voyag-", radicalVous: "voyag-" },
  { infinitif: "partager",    groupe: 1, niveau: 2, radicalImp: "partage-",    radicalNous: "partag-", radicalVous: "partag-" },
  { infinitif: "obliger",     groupe: 1, niveau: 2, radicalImp: "oblige-",     radicalNous: "oblig-", radicalVous: "oblig-" },
  { infinitif: "corriger",    groupe: 1, niveau: 2, radicalImp: "corrige-",    radicalNous: "corrig-", radicalVous: "corrig-" },
  { infinitif: "interroger",  groupe: 1, niveau: 3, radicalImp: "interroge-",  radicalNous: "interrog-", radicalVous: "interrog-" },
  { infinitif: "déménager",   groupe: 1, niveau: 3, radicalImp: "déménage-",   radicalNous: "déménag-", radicalVous: "déménag-" },
  // --- Verbes en -CER (cédille sauf nous/vous) ---
  { infinitif: "lancer",      groupe: 1, niveau: 1, radicalImp: "lanç-",       radicalNous: "lanc-", radicalVous: "lanc-" },
  { infinitif: "avancer",     groupe: 1, niveau: 1, radicalImp: "avanç-",      radicalNous: "avanc-", radicalVous: "avanc-" },
  { infinitif: "placer",      groupe: 1, niveau: 1, radicalImp: "plaç-",       radicalNous: "plac-", radicalVous: "plac-" },
  { infinitif: "commencer",   groupe: 1, niveau: 1, radicalImp: "commenç-",    radicalNous: "commenc-", radicalVous: "commenc-" },
  { infinitif: "effacer",     groupe: 1, niveau: 2, radicalImp: "effaç-",      radicalNous: "effac-", radicalVous: "effac-" },
  { infinitif: "tracer",      groupe: 1, niveau: 2, radicalImp: "traç-",       radicalNous: "trac-", radicalVous: "trac-" },
  { infinitif: "menacer",     groupe: 1, niveau: 2, radicalImp: "menaç-",      radicalNous: "menac-", radicalVous: "menac-" },
  { infinitif: "annoncer",    groupe: 1, niveau: 2, radicalImp: "annonç-",     radicalNous: "annonc-", radicalVous: "annonc-" },
  { infinitif: "prononcer",   groupe: 1, niveau: 2, radicalImp: "prononç-",    radicalNous: "prononc-", radicalVous: "prononc-" },
  { infinitif: "forcer",      groupe: 1, niveau: 3, radicalImp: "forç-",       radicalNous: "forc-", radicalVous: "forc-" },
  { infinitif: "lacer",       groupe: 1, niveau: 3, radicalImp: "laç-",        radicalNous: "lac-", radicalVous: "lac-" },
  { infinitif: "agacer",      groupe: 1, niveau: 3, radicalImp: "agaç-",       radicalNous: "agac-", radicalVous: "agac-" },
  { infinitif: "recommencer", groupe: 1, niveau: 3, radicalImp: "recommenç-",  radicalNous: "recommenc-", radicalVous: "recommenc-" },
  { infinitif: "devancer",    groupe: 1, niveau: 4, radicalImp: "devanç-",     radicalNous: "devanc-", radicalVous: "devanc-" },
  { infinitif: "balancer",    groupe: 1, niveau: 4, radicalImp: "balanç-",     radicalNous: "balanc-", radicalVous: "balanc-" },
];